/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlycafemangdi.view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import quanlycafemangdi.model.LichSuChinhSuaNguyenLieu;
import java.sql.*;
import quanlycafemangdi.Design;
import quanlycafemangdi.Util;
/**
 *
 * @author admin
 */
public class LichSuChinhSuaNguyenLieu_Frame extends javax.swing.JFrame {

    private DefaultTableModel dtmLichSuChinhSuaNguyenLieu;
    
    private ArrayList<LichSuChinhSuaNguyenLieu> danhSachChinhSuaNguyenLieu = new ArrayList<>();
    
    private String truongHop = "";

    public LichSuChinhSuaNguyenLieu_Frame(String truongHop) {
        initComponents();
             
        if (truongHop.equals("NguyenLieu"))
        {
            khoiTaoBang("NguyenLieu");
            Design.thietKeBang(lichSuChinhSuaNguyenLieu_Table, "Lon");

            layDanhSachChinhSuaNguyenLieu();
            hienThiDanhSachChinhSuaNguyenLieu();               
        }        
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lichSuChinhSuaNguyenLieu_Table = new javax.swing.JTable();
        lichSuChinhSuaNguyenLieu_Lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lichSuChinhSuaNguyenLieu_Table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lichSuChinhSuaNguyenLieu_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(lichSuChinhSuaNguyenLieu_Table);

        lichSuChinhSuaNguyenLieu_Lbl.setBackground(new java.awt.Color(114, 102, 186));
        lichSuChinhSuaNguyenLieu_Lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lichSuChinhSuaNguyenLieu_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        lichSuChinhSuaNguyenLieu_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lichSuChinhSuaNguyenLieu_Lbl.setText("Lịch sử chỉnh sửa");
        lichSuChinhSuaNguyenLieu_Lbl.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1264, Short.MAX_VALUE)
            .addComponent(lichSuChinhSuaNguyenLieu_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lichSuChinhSuaNguyenLieu_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LichSuChinhSuaNguyenLieu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LichSuChinhSuaNguyenLieu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LichSuChinhSuaNguyenLieu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LichSuChinhSuaNguyenLieu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LichSuChinhSuaNguyenLieu_Frame("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lichSuChinhSuaNguyenLieu_Lbl;
    private javax.swing.JTable lichSuChinhSuaNguyenLieu_Table;
    // End of variables declaration//GEN-END:variables

    public void khoiTaoBang(String truongHop)
    {
        if (truongHop.equals("NguyenLieu"))
        {
        dtmLichSuChinhSuaNguyenLieu = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) 
        {
            return false;
        }};
        dtmLichSuChinhSuaNguyenLieu.setColumnIdentifiers(new Object[]
        {
            "Thời gian", "Mã nguyên liệu", "Tên nguyên liệu", "Đơn vị tính", "Giá", "Người thực hiện", "Ghi chú"
        });
        lichSuChinhSuaNguyenLieu_Table.setModel(dtmLichSuChinhSuaNguyenLieu);             
        }
                 
    }
    
    public void layDanhSachChinhSuaNguyenLieu()
    {
        Connection connect = Util.getConnection();
        String query = "select * from LichSuChinhSuaNguyenLieu order by thoiGian, ghiChu desc";
        try
        {
            PreparedStatement ps = connect.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next())
            {
                LichSuChinhSuaNguyenLieu lichSuChinhSuaNguyenLieu = new LichSuChinhSuaNguyenLieu();
                lichSuChinhSuaNguyenLieu.setThoiGian(rs.getTimestamp("thoiGian"));
                lichSuChinhSuaNguyenLieu.setMaNguyenLieu(rs.getString("maNL"));
                lichSuChinhSuaNguyenLieu.setTenNguyenLieu(rs.getString("tenNL"));
                lichSuChinhSuaNguyenLieu.setMaDonVi(rs.getString("maDV"));
                lichSuChinhSuaNguyenLieu.setDonViTinh(lichSuChinhSuaNguyenLieu.layDonViTinh());
                lichSuChinhSuaNguyenLieu.setGia(rs.getLong("gia"));
                lichSuChinhSuaNguyenLieu.setNguoiThucHien(rs.getString("nguoiThucHien"));
                lichSuChinhSuaNguyenLieu.setGhiChu(rs.getString("ghiChu"));
                danhSachChinhSuaNguyenLieu.add(lichSuChinhSuaNguyenLieu);
            }
            rs.close();
            ps.close();
            connect.close();
        }catch (SQLException ex)
        {
            ex.printStackTrace();
        }
    }
    
    public void hienThiDanhSachChinhSuaNguyenLieu()
    {
        dtmLichSuChinhSuaNguyenLieu.setRowCount(0);
        for (LichSuChinhSuaNguyenLieu lichSuChinhSuaNguyenLieu: danhSachChinhSuaNguyenLieu)
        {
            String thoiGian = lichSuChinhSuaNguyenLieu.getThoiGian().toString();
            dtmLichSuChinhSuaNguyenLieu.addRow(new Object[]
            {
                lichSuChinhSuaNguyenLieu.dinhDangThoiGianNgayThangNam(thoiGian), lichSuChinhSuaNguyenLieu.getMaNguyenLieu(),
                lichSuChinhSuaNguyenLieu.getTenNguyenLieu(), lichSuChinhSuaNguyenLieu.getDonViTinh(), Util.formatCurrency(lichSuChinhSuaNguyenLieu.getGia()),
                lichSuChinhSuaNguyenLieu.getNguoiThucHien(), lichSuChinhSuaNguyenLieu.getGhiChu()
            });                
        }
    }
    
}
