/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlycafemangdi.view;

import java.util.ArrayList;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import quanlycafemangdi.Util;
import quanlycafemangdi.model.NguyenLieu;
import quanlycafemangdi.model.NhapXuat;

/**
 *
 * @author admin
 */
public class NguyenLieu_HienThiNguyenLieuNhapXuatFrame extends javax.swing.JFrame {
    
    private ArrayList<NguyenLieu> danhSachNguyenLieu = new ArrayList<>();
        
    private NhapXuat nhapXuat;
    
    private DefaultTableModel dtmDanhSachNguyenLieuNhap;
    private DefaultTableModel dtmDanhSachNguyenLieuXuat;
    
    public NguyenLieu_HienThiNguyenLieuNhapXuatFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        danhSachNguyenLieuNhapXuat_Lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhSachNguyenLieuNhapXuat_Table = new javax.swing.JTable();
        quayLai_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        danhSachNguyenLieuNhapXuat_Lbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        danhSachNguyenLieuNhapXuat_Lbl.setText("Danh sách nguyên liệu");

        danhSachNguyenLieuNhapXuat_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(danhSachNguyenLieuNhapXuat_Table);

        quayLai_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/quayLai.png"))); // NOI18N
        quayLai_Btn.setText("Quay lại");
        quayLai_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quayLai_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(quayLai_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(danhSachNguyenLieuNhapXuat_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quayLai_Btn)
                    .addComponent(danhSachNguyenLieuNhapXuat_Lbl))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quayLai_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quayLai_BtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_quayLai_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NguyenLieu_HienThiNguyenLieuNhapXuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NguyenLieu_HienThiNguyenLieuNhapXuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NguyenLieu_HienThiNguyenLieuNhapXuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NguyenLieu_HienThiNguyenLieuNhapXuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NguyenLieu_HienThiNguyenLieuNhapXuatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel danhSachNguyenLieuNhapXuat_Lbl;
    private javax.swing.JTable danhSachNguyenLieuNhapXuat_Table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton quayLai_Btn;
    // End of variables declaration//GEN-END:variables
        
    public void khoiTaoBangChiTietNhap()
    {
        dtmDanhSachNguyenLieuNhap = new DefaultTableModel(){
        @Override
            public boolean isCellEditable(int row, int column) 
            {
                return false;
            }
        };
        dtmDanhSachNguyenLieuNhap.setColumnIdentifiers(new Object[]
        {
            "Mã nguyên liệu", "Tên nguyên liệu", "Đơn vị tính", "Giá", "Số lượng nhập", "Thành tiền"
        });      
        danhSachNguyenLieuNhapXuat_Table.setModel(dtmDanhSachNguyenLieuNhap);        
    }
    
    public void khoiTaoBangChiTietXuat()
    {
        dtmDanhSachNguyenLieuXuat = new DefaultTableModel(){
        @Override
            public boolean isCellEditable(int row, int column) 
            {
                return false;
            }
        };
        dtmDanhSachNguyenLieuXuat.setColumnIdentifiers(new Object[]
        {
            "Mã nguyên liệu", "Tên nguyên liệu", "Đơn vị tính", "Giá", "Số lượng xuất"
        });      
        danhSachNguyenLieuNhapXuat_Table.setModel(dtmDanhSachNguyenLieuXuat);        
    }    
    
    public void hienThiNguyenLieuNhap(String trangThai)
    {
        if (trangThai.equals("0"))
        {
            Set<String> keySet = nhapXuat.getChiTietNhapXuat().keySet();
            for (String key: keySet)
            {
                for (int i = 0; i < danhSachNguyenLieu.size(); i++)
                {
                    if (danhSachNguyenLieu.get(i).getMaNguyenLieu().equals(key))
                    {
                        long gia = danhSachNguyenLieu.get(i).getGia();
                        int soLuong = nhapXuat.getChiTietNhapXuat().get(key);
                        long thanhTien = gia*soLuong;
                        dtmDanhSachNguyenLieuNhap.addRow(new Object[]
                        {
                            danhSachNguyenLieu.get(i).getMaNguyenLieu(), danhSachNguyenLieu.get(i).getTenNguyenLieu(),
                            danhSachNguyenLieu.get(i).getDonViTinh(), Util.formatCurrency(gia), soLuong, 
                            Util.formatCurrency(thanhTien)
                        });
                    }
                }
            }            
        }
        else // Khong hien thi thanh tien khi tra nguyen lieu
        {
            Set<String> keySet = nhapXuat.getChiTietNhapXuat().keySet();
            for (String key: keySet)
            {
                for (int i = 0; i < danhSachNguyenLieu.size(); i++)
                {
                    if (danhSachNguyenLieu.get(i).getMaNguyenLieu().equals(key))
                    {
                        long gia = danhSachNguyenLieu.get(i).getGia();
                        int soLuong = nhapXuat.getChiTietNhapXuat().get(key);
                        dtmDanhSachNguyenLieuNhap.addRow(new Object[]
                        {
                            danhSachNguyenLieu.get(i).getMaNguyenLieu(), danhSachNguyenLieu.get(i).getTenNguyenLieu(),
                            danhSachNguyenLieu.get(i).getDonViTinh(), Util.formatCurrency(gia), soLuong, 
                            "0"
                        });
                    }
                }
            }            
        }

    }
    
    public void hienThiNguyenLieuXuat()
    {       
        Set<String> keySet = nhapXuat.getChiTietNhapXuat().keySet();
        for (String key: keySet)
        {
            for (int i = 0; i < danhSachNguyenLieu.size(); i++)
            {
                if (danhSachNguyenLieu.get(i).getMaNguyenLieu().equals(key))
                {
                    long gia = danhSachNguyenLieu.get(i).getGia();
                    int soLuong = nhapXuat.getChiTietNhapXuat().get(key);
                    dtmDanhSachNguyenLieuXuat.addRow(new Object[]
                    {
                        danhSachNguyenLieu.get(i).getMaNguyenLieu(), danhSachNguyenLieu.get(i).getTenNguyenLieu(),
                        danhSachNguyenLieu.get(i).getDonViTinh(), Util.formatCurrency(gia), soLuong
                    });
                }
            }
        }
    }    
    
    public void setNhapXuat(NhapXuat nhapXuat) {
        this.nhapXuat = nhapXuat;
    }

    public void setDanhSachNguyenLieu(ArrayList<NguyenLieu> danhSachNguyenLieu) {
        this.danhSachNguyenLieu = danhSachNguyenLieu;
    }    
}
