/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlycafemangdi.view;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import quanlycafemangdi.model.NguyenLieu;
import java.sql.*;
import java.util.ArrayList;
import quanlycafemangdi.Util;
import quanlycafemangdi.model.ChiTietNhapXuat;
import quanlycafemangdi.model.ThongTinDangNhap;
/**
 *
 * @author admin
 */
public class NguyenLieu_NhapXuatFrame extends javax.swing.JFrame {

    private NguyenLieu nguyenLieu;
    
    private IOnFrameDispose onFrameDispose;
    
    private ArrayList<String> danhSachMaNhapXuat = new ArrayList<>();
    private ArrayList<ChiTietNhapXuat> danhSachNhap = new ArrayList<>();
    private ArrayList<ChiTietNhapXuat> danhSachXuat = new ArrayList<>();
    /**
     * Creates new form NhapNguyenLieuFrame
     */
    public NguyenLieu_NhapXuatFrame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        nhap_RBtn.setActionCommand("Nhập");
        xuat_RBtn.setActionCommand("Xuất");
        
        ghiChu_TA.setText("Nhập nguyên liệu về kho");
        
        thietLapGhiChu();
        
        layDanhSachMaNhapXuat(danhSachMaNhapXuat);       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nhapXuat_BtnG = new javax.swing.ButtonGroup();
        nhapXuatNguyenLieu_Lbl = new javax.swing.JLabel();
        maNguyenLieu_Lbl = new javax.swing.JLabel();
        maNguyenLieu_TF = new javax.swing.JTextField();
        tenNguyenLieu_Lbl = new javax.swing.JLabel();
        tenNguyenLieu_TF = new javax.swing.JTextField();
        donViTinh_Lbl = new javax.swing.JLabel();
        donViTinh_TF = new javax.swing.JTextField();
        gia_Lbl = new javax.swing.JLabel();
        gia_TF = new javax.swing.JTextField();
        soLuongTon_Lbl = new javax.swing.JLabel();
        soLuongTon_TF = new javax.swing.JTextField();
        nhapXuat_Lbl = new javax.swing.JLabel();
        soLuongNhapXuat_Lbl = new javax.swing.JLabel();
        ghiChu_Lbl = new javax.swing.JLabel();
        soLuongNhapXuat_TF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ghiChu_TA = new javax.swing.JTextArea();
        huy_Btn = new javax.swing.JButton();
        xacNhan_Btn = new javax.swing.JButton();
        nhap_RBtn = new javax.swing.JRadioButton();
        xuat_RBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nhapXuatNguyenLieu_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nhapXuatNguyenLieu_Lbl.setText("Nhập/xuất nguyên liệu");

        maNguyenLieu_Lbl.setText("Mã nguyên liệu");

        maNguyenLieu_TF.setEditable(false);

        tenNguyenLieu_Lbl.setText("Tên nguyên liệu");

        tenNguyenLieu_TF.setEditable(false);

        donViTinh_Lbl.setText("Đơn vị tính");

        donViTinh_TF.setEditable(false);

        gia_Lbl.setText("Giá");

        gia_TF.setEditable(false);

        soLuongTon_Lbl.setText("Số lượng tồn");

        soLuongTon_TF.setEditable(false);

        nhapXuat_Lbl.setText("Nhập/xuất");

        soLuongNhapXuat_Lbl.setText("Số lượng nhập/xuất");

        ghiChu_Lbl.setText("Ghi chú");

        ghiChu_TA.setColumns(20);
        ghiChu_TA.setRows(5);
        jScrollPane1.setViewportView(ghiChu_TA);

        huy_Btn.setText("Hủy");
        huy_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huy_BtnActionPerformed(evt);
            }
        });

        xacNhan_Btn.setText("Xác nhận");
        xacNhan_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacNhan_BtnActionPerformed(evt);
            }
        });

        nhapXuat_BtnG.add(nhap_RBtn);
        nhap_RBtn.setSelected(true);
        nhap_RBtn.setText("Nhập");

        nhapXuat_BtnG.add(xuat_RBtn);
        xuat_RBtn.setText("Xuất");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ghiChu_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(soLuongNhapXuat_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(soLuongNhapXuat_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nhapXuat_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nhap_RBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(xuat_RBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(soLuongTon_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(soLuongTon_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(gia_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gia_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(donViTinh_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(donViTinh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tenNguyenLieu_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tenNguyenLieu_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maNguyenLieu_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maNguyenLieu_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nhapXuatNguyenLieu_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(xacNhan_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(huy_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(nhapXuatNguyenLieu_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(maNguyenLieu_TF)
                    .addComponent(maNguyenLieu_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tenNguyenLieu_TF)
                    .addComponent(tenNguyenLieu_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(donViTinh_TF)
                    .addComponent(donViTinh_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gia_TF)
                    .addComponent(gia_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(soLuongTon_TF)
                    .addComponent(soLuongTon_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhapXuat_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhap_RBtn)
                    .addComponent(xuat_RBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soLuongNhapXuat_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(soLuongNhapXuat_TF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(ghiChu_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xacNhan_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huy_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void huy_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huy_BtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_huy_BtnActionPerformed

    private void xacNhan_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacNhan_BtnActionPerformed
        nhapXuatNguyenLieu();
    }//GEN-LAST:event_xacNhan_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NguyenLieu_NhapXuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NguyenLieu_NhapXuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NguyenLieu_NhapXuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NguyenLieu_NhapXuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NguyenLieu_NhapXuatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel donViTinh_Lbl;
    private javax.swing.JTextField donViTinh_TF;
    private javax.swing.JLabel ghiChu_Lbl;
    private javax.swing.JTextArea ghiChu_TA;
    private javax.swing.JLabel gia_Lbl;
    private javax.swing.JTextField gia_TF;
    private javax.swing.JButton huy_Btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maNguyenLieu_Lbl;
    private javax.swing.JTextField maNguyenLieu_TF;
    private javax.swing.JLabel nhapXuatNguyenLieu_Lbl;
    private javax.swing.ButtonGroup nhapXuat_BtnG;
    private javax.swing.JLabel nhapXuat_Lbl;
    private javax.swing.JRadioButton nhap_RBtn;
    private javax.swing.JLabel soLuongNhapXuat_Lbl;
    private javax.swing.JTextField soLuongNhapXuat_TF;
    private javax.swing.JLabel soLuongTon_Lbl;
    private javax.swing.JTextField soLuongTon_TF;
    private javax.swing.JLabel tenNguyenLieu_Lbl;
    private javax.swing.JTextField tenNguyenLieu_TF;
    private javax.swing.JButton xacNhan_Btn;
    private javax.swing.JRadioButton xuat_RBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dispose() 
    {
        onFrameDispose.onFrameDispose();
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }    
    
    public void setOnFrameDispose(IOnFrameDispose onFrameDispose){
        this.onFrameDispose = onFrameDispose;
    }

    public void setDanhSachNhap(ArrayList<ChiTietNhapXuat> danhSachNhap) {
        this.danhSachNhap = danhSachNhap;
    }

    public void setDanhSachXuat(ArrayList<ChiTietNhapXuat> danhSachXuat) {
        this.danhSachXuat = danhSachXuat;
    }    
    
    public void thietLapDuLieu(NguyenLieu nguyenLieu)
    {
        this.nguyenLieu = nguyenLieu;
        
        maNguyenLieu_TF.setText(nguyenLieu.getMaNguyenLieu());
        tenNguyenLieu_TF.setText(nguyenLieu.getTenNguyenLieu());
        donViTinh_TF.setText(nguyenLieu.getDonViTinh());
        gia_TF.setText(nguyenLieu.getGia() + "");
        soLuongTon_TF.setText(nguyenLieu.getSoLuong() + "");          
    }    
    
    public void thietLapGhiChu()
    {
        nhap_RBtn.addItemListener(new ItemListener()
        {
            @Override
            public void itemStateChanged(ItemEvent e) 
            {
                ghiChu_TA.setText("Nhập nguyên liệu về kho");
            }           
        });
        xuat_RBtn.addItemListener(new ItemListener()
        {
            @Override
            public void itemStateChanged(ItemEvent e) 
            {
                ghiChu_TA.setText("Xuất nguyên liệu");
            }           
        });
    }        
 
    public void layDanhSachMaNhapXuat(ArrayList<String> danhSachMaNhapXuat)
    {
        Connection connect = Util.getConnection();
        String query = "select * from NhapXuat";
        try
        {
            PreparedStatement ps = connect.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next())
            {
                danhSachMaNhapXuat.add(rs.getString("maNX"));
            }
        }catch (SQLException ex)
        {
            System.out.println("Lay danh sach ma nhap xuat that bai");
        }       
    }
    
    public String taoMaNhapXuat()
    {
        int STT = 0;
        String maNhapXuat = "";
        if (nhapXuat_BtnG.getSelection().getActionCommand() == "Nhập")
        {
            maNhapXuat = "N" + String.valueOf(STT);
            while (danhSachMaNhapXuat.contains(maNhapXuat))
            {
                STT++;
                maNhapXuat = "N" + String.valueOf(STT);
            }            
        }
        else if (nhapXuat_BtnG.getSelection().getActionCommand() == "Xuất")
        {
            maNhapXuat = "X" + String.valueOf(STT);
            while (danhSachMaNhapXuat.contains(maNhapXuat))
            {
                STT++;
                maNhapXuat = "X" + String.valueOf(STT);
            }            
        }
        return maNhapXuat;
    }
    
    public void nhapXuatNguyenLieu()
    {
        String maNhapXuat = taoMaNhapXuat();
        String tenTK = ThongTinDangNhap.getTenDangNhap();
        java.sql.Timestamp thoiGian = new java.sql.Timestamp(new java.util.Date().getTime());
        String trangThai = nhapXuat_BtnG.getSelection().getActionCommand();
        String ghiChu = ghiChu_TA.getText();
        String maNguyenLieu = maNguyenLieu_TF.getText();
        String soLuongNhapXuat = soLuongNhapXuat_TF.getText();
        
        if (soLuongNhapXuat.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng cho biết số lượng nhập/xuất");
        }
        else if (soLuongNhapXuat.matches("\\d+") == false)
        {
            JOptionPane.showMessageDialog(rootPane, "Số lượng nhập/xuất phải là số nguyên", "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if (trangThai.equals("Nhập"))
            {
                nhapXuatNguyenLieuSQL(maNhapXuat, tenTK, thoiGian, "Nhập", ghiChu, maNguyenLieu, 
                        Integer.parseInt(soLuongNhapXuat));
                JOptionPane.showMessageDialog(rootPane, "Nhập nguyên liệu thành công");
                nguyenLieu.setSoLuong(nguyenLieu.getSoLuong() + Integer.parseInt(soLuongNhapXuat));
                ChiTietNhapXuat chiTietNhap = new ChiTietNhapXuat();
                chiTietNhap.setMaNguyenLieu(maNguyenLieu);
                chiTietNhap.setTenNguyenLieu(tenNguyenLieu_TF.getText());
                chiTietNhap.setSoLuong(Integer.parseInt(soLuongNhapXuat));
                chiTietNhap.setTaiKhoan(tenTK);
                String thoiGianMoi = chiTietNhap.dinhDangThoiGianNgayThangNam(thoiGian.toString());
                chiTietNhap.setThoiGian(thoiGianMoi);
                chiTietNhap.setThanhTien(nguyenLieu.getGia()* Integer.parseInt(soLuongNhapXuat));
                chiTietNhap.setGhiChu(ghiChu);
                danhSachNhap.add(chiTietNhap);
                this.dispose();
            }
            else if (trangThai.equals("Xuất"))
            {
                if (Integer.parseInt(soLuongNhapXuat) > nguyenLieu.getSoLuong())
                {
                    JOptionPane.showMessageDialog(rootPane, "Số lượng xuất không thể vượt quá số lượng tồn",
                            "Xuất nguyên liệu thất bại", JOptionPane.ERROR_MESSAGE);                        
                }
                else
                {
                    nhapXuatNguyenLieuSQL(maNhapXuat, tenTK, thoiGian, "Xuất", ghiChu, maNguyenLieu, 
                            Integer.parseInt(soLuongNhapXuat));
                    JOptionPane.showMessageDialog(rootPane, "Xuất nguyên liệu thành công");
                    nguyenLieu.setSoLuong(nguyenLieu.getSoLuong() - Integer.parseInt(soLuongNhapXuat));
                    ChiTietNhapXuat chiTietXuat = new ChiTietNhapXuat();
                    chiTietXuat.setMaNguyenLieu(maNguyenLieu);
                    chiTietXuat.setTenNguyenLieu(tenNguyenLieu_TF.getText());
                    chiTietXuat.setSoLuong(Integer.parseInt(soLuongNhapXuat));
                    chiTietXuat.setTaiKhoan(tenTK);
                    String thoiGianMoi = chiTietXuat.dinhDangThoiGianNgayThangNam(thoiGian.toString());
                    chiTietXuat.setThoiGian(thoiGianMoi);
                    chiTietXuat.setThanhTien(nguyenLieu.getGia()* Integer.parseInt(soLuongNhapXuat));
                    chiTietXuat.setGhiChu(ghiChu);
                    danhSachXuat.add(chiTietXuat);                    
                    this.dispose();    
                }
            }
        }
    }
       
    public void nhapXuatNguyenLieuSQL(String maNhapXuat, String tenTK, Timestamp thoiGian, String trangThai, String ghiChu,
            String maNguyenLieu, int soLuongNhapXuat)
    {
        if (trangThai.equals("Nhập"))
        {
            trangThai = "0";
            Connection connect = Util.getConnection();
            String query = "insert into NhapXuat values (?,?,?,?,?)"
                        +  " insert into ChiTietNhapXuat values (?,?,?)"
                        +  " update NguyenLieu"
                        +  "   set SoLuong = SoLuong + " + soLuongNhapXuat
                        +  "   where maNL = '" + maNguyenLieu + "'";
            try
            {
                PreparedStatement ps = connect.prepareStatement(query);
                ps.setString(1, maNhapXuat);
                ps.setString(2, tenTK);
                ps.setTimestamp(3, thoiGian);
                ps.setString(4, trangThai);
                ps.setString(5, ghiChu);
                ps.setString(6, maNhapXuat);
                ps.setString(7, maNguyenLieu);
                ps.setInt(8, soLuongNhapXuat);
                ps.executeUpdate();
                ps.close();
                connect.close();
            }catch (SQLException ex)
            {
                System.out.println("Nhap nguyen lieu that bai");
            }            
        }
        else if (trangThai.equals("Xuất"))
        {
            trangThai = "1";
            Connection connect = Util.getConnection();
            String query = "insert into NhapXuat values (?,?,?,?,?)"
                        +  " insert into ChiTietNhapXuat values (?,?,?)"
                        +  " update NguyenLieu"
                        +  "   set SoLuong = SoLuong - " + soLuongNhapXuat
                        +  "   where maNL = '" + maNguyenLieu + "'";
            try
            {
                PreparedStatement ps = connect.prepareStatement(query);
                ps.setString(1, maNhapXuat);
                ps.setString(2, tenTK);
                ps.setTimestamp(3, thoiGian);
                ps.setString(4, trangThai);
                ps.setString(5, ghiChu);
                ps.setString(6, maNhapXuat);
                ps.setString(7, maNguyenLieu);
                ps.setInt(8, soLuongNhapXuat);
                ps.executeUpdate();
                ps.close();
                connect.close();
            }catch (SQLException ex)
            {
                System.out.println("Xuat nguyen lieu that bai");
            }                        
        }
    }    
}
