/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlycafemangdi.view;

import javax.swing.JOptionPane;
import java.sql.*;
import quanlycafemangdi.Util;
import java.util.Date;
import quanlycafemangdi.model.Email;
import quanlycafemangdi.speedsms.SendMessage;
/**
 *
 * @author admin
 */
public class QuenMatKhauDialog extends javax.swing.JDialog {

    private DangNhap home;
    private String loi;
    private String tenNhanVien;
    
    public QuenMatKhauDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        home = (DangNhap)parent;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        khoiPhucMatKhau_Lbl = new javax.swing.JLabel();
        taiKhoan_Lbl = new javax.swing.JLabel();
        CMND_Lbl = new javax.swing.JLabel();
        taiKhoan_TF = new javax.swing.JTextField();
        CMND_TF = new javax.swing.JTextField();
        guiYeuCau_Btn = new javax.swing.JButton();
        huy_Btn = new javax.swing.JButton();
        SDT_Lbl = new javax.swing.JLabel();
        SDT_TF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Khôi phục mật khẩu");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        khoiPhucMatKhau_Lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        khoiPhucMatKhau_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        khoiPhucMatKhau_Lbl.setText("Khôi phục mật khẩu");

        taiKhoan_Lbl.setText("Tài khoản:");

        CMND_Lbl.setText("CMND/CCCD:");

        guiYeuCau_Btn.setBackground(new java.awt.Color(0, 102, 255));
        guiYeuCau_Btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        guiYeuCau_Btn.setForeground(new java.awt.Color(255, 255, 255));
        guiYeuCau_Btn.setText("Gửi yêu cầu");
        guiYeuCau_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiYeuCau_BtnActionPerformed(evt);
            }
        });

        huy_Btn.setBackground(new java.awt.Color(0, 102, 255));
        huy_Btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        huy_Btn.setForeground(new java.awt.Color(255, 255, 255));
        huy_Btn.setText("Hủy");
        huy_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huy_BtnActionPerformed(evt);
            }
        });

        SDT_Lbl.setText("SĐT:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(taiKhoan_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CMND_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(taiKhoan_TF)
                                .addComponent(CMND_TF)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(guiYeuCau_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(huy_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(khoiPhucMatKhau_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SDT_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDT_TF)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(khoiPhucMatKhau_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taiKhoan_Lbl)
                    .addComponent(taiKhoan_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMND_Lbl)
                    .addComponent(CMND_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SDT_Lbl)
                    .addComponent(SDT_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiYeuCau_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huy_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guiYeuCau_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiYeuCau_BtnActionPerformed
        if (kiemTraLoi() == false)
        {
            guiYeuCauKhoiPhucMatKhau();
        }
    }//GEN-LAST:event_guiYeuCau_BtnActionPerformed

    private void huy_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huy_BtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_huy_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhauDialog dialog = new QuenMatKhauDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CMND_Lbl;
    private javax.swing.JTextField CMND_TF;
    private javax.swing.JLabel SDT_Lbl;
    private javax.swing.JTextField SDT_TF;
    private javax.swing.JButton guiYeuCau_Btn;
    private javax.swing.JButton huy_Btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel khoiPhucMatKhau_Lbl;
    private javax.swing.JLabel taiKhoan_Lbl;
    private javax.swing.JTextField taiKhoan_TF;
    // End of variables declaration//GEN-END:variables

// ========================== SMS =================================
    public boolean kiemTraLoi()
    {   
        loi = "";

        String taiKhoan = taiKhoan_TF.getText();
        String CMND = CMND_TF.getText();
        String SDT = SDT_TF.getText();

        if (taiKhoan.equals(""))
        {
            loi = loi + "Tài khoản không được để trống\n";
        }

        if (CMND.equals(""))
        {
            loi = loi + "CMND/CCCD không được để trống\n";
        }
        
        if (SDT.equals(""))
        {
            loi = loi + "SĐT không được để trống\n";
        }

        if (loi.equals("") == false)
        {
            hienThiLoi(loi);
            return true;
        }
        else
        {
            return false;
        }
    }    
    
    public void hienThiLoi(String loi)
    {
        JOptionPane.showMessageDialog(rootPane, loi, "Lỗi", JOptionPane.ERROR_MESSAGE);
    }     
    
    public boolean kiemTraThongTin(String taiKhoan, String CMND, String SDT)
    {
        Connection connect = Util.getConnection();
        String query = "select * from NhanVien where tenTK = '" + taiKhoan + "' and cmnd = '" + CMND + "'"
                     + " and sdt = '" + SDT + "'";
        try
        {
            PreparedStatement ps = connect.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            if (rs.next())
            {
                return true;
            }
        }catch (SQLException ex)
        {
            ex.printStackTrace();
        }
        return false;
    }
    
    public void guiYeuCauKhoiPhucMatKhau()
    {
        String taiKhoan = taiKhoan_TF.getText();
        String CMND = CMND_TF.getText();
        String SDT = SDT_TF.getText();
        
        if (kiemTraThongTin(taiKhoan, CMND, SDT) == false)
        {
            JOptionPane.showMessageDialog(rootPane, "Thông tin không chính xác. Vui lòng kiểm tra lại\n",
                    "Lỗi!", JOptionPane.ERROR_MESSAGE);
            return;
        }        
        
        String matKhauMoi = taoMatKhauMoi();
        
        Connection connect = Util.getConnection();
        String query = "update NhanVien set matKhau = '" + Util.hashing(matKhauMoi) + "'"
                     + " where tenTK = '" + taiKhoan + "' and cmnd = '" + CMND + "'"
                     + " and sdt = '" + SDT + "'";
        try
        {
            PreparedStatement ps = connect.prepareStatement(query);
            ps.executeUpdate();
            SendMessage.sendMessage(SendMessage.defaultToken, SDT, "Mật khẩu mới: " + matKhauMoi, SendMessage.defaultSenderID);
        }catch (SQLException ex)
        {
            ex.printStackTrace();
        }
            
        JOptionPane.showMessageDialog(rootPane, "Gửi yêu cầu khôi phục mật khẩu thành công");
        clear();
    }
    
    public String taoMatKhauMoi()
    {
        Date date = new Date();
        long timeMilli = date.getTime();
        return (timeMilli % 100000000)  + "";    
    }
    
    public void clear()
    {
        taiKhoan_TF.setText("");
        CMND_TF.setText("");
        SDT_TF.setText("");
    }
    
 // ====================== Email (sua bien SDT_TF cua frame thanh email_TF de su dung) =================
//    public boolean kiemTraLoi()
//    {   
//        loi = "";
//
//        String taiKhoan = taiKhoan_TF.getText();
//        String CMND = CMND_TF.getText();
//        String email = email_TF.getText();
//
//        if (taiKhoan.equals(""))
//        {
//            loi = loi + "Tài khoản không được để trống\n";
//        }
//
//        if (CMND.equals(""))
//        {
//            loi = loi + "CMND/CCCD không được để trống\n";
//        }
//        
//        if (email.equals(""))
//        {
//            loi = loi + "Email không được để trống\n";
//        }
//
//        if (loi.equals("") == false)
//        {
//            hienThiLoi(loi);
//            return true;
//        }
//        else
//        {
//            return false;
//        }
//    }    
//    
//    public void hienThiLoi(String loi)
//    {
//        JOptionPane.showMessageDialog(rootPane, loi, "Lỗi", JOptionPane.ERROR_MESSAGE);
//    }     
//    
//    public boolean kiemTraThongTin(String taiKhoan, String CMND)
//    {
//        Connection connect = Util.getConnection();
//        String query = "select * from NhanVien where tenTK = '" + taiKhoan + "' and cmnd = '" + CMND + "'";
//        try
//        {
//            PreparedStatement ps = connect.prepareStatement(query);
//            ResultSet rs = ps.executeQuery();
//            if (rs.next())
//            {
//                this.tenNhanVien = rs.getString("tenNV");
//                return true;
//            }
//        }catch (SQLException ex)
//        {
//            ex.printStackTrace();
//        }
//        return false;
//    }
//    
//    public void guiYeuCauKhoiPhucMatKhau()
//    {
//        String taiKhoan = taiKhoan_TF.getText();
//        String CMND = CMND_TF.getText();
//        String email = email_TF.getText();
//        
//        if (kiemTraThongTin(taiKhoan, CMND) == false)
//        {
//            JOptionPane.showMessageDialog(rootPane, "Thông tin không chính xác. Vui lòng kiểm tra lại\n",
//                    "Lỗi!", JOptionPane.ERROR_MESSAGE);
//            return;
//        }       
//        
//        String matKhauMoi = taoMatKhauMoi();
//        
//        Connection connect = Util.getConnection();
//        String query = "update NhanVien set matKhau = '" + Util.hashing(matKhauMoi) + "'"
//                     + " where tenTK = '" + taiKhoan + "' and cmnd = '" + CMND + "'";
//        try
//        {
//            PreparedStatement ps = connect.prepareStatement(query);
//            ps.executeUpdate();
//            String noiDung = "A+ CNPM\n\n"
//                           + "Nhân viên: " + tenNhanVien + "\n"
//                           + "Tài khoản: " + taiKhoan + "\n"
//                           + "Mật khẩu mới: " + matKhauMoi;
//            if (Email.guiEmail(email, "doimatkhauQLCTA@gmail.com", "qlcta123!", "smtp.gmail.com", noiDung) == true)
//            {
//                JOptionPane.showMessageDialog(rootPane, "Gửi yêu cầu khôi phục mật khẩu thành công");
//                clear();
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(rootPane, "Gửi yêu cầu không thành công.", "Lỗi!", 
//                        JOptionPane.ERROR_MESSAGE);                  
//            }
//        }catch (SQLException ex)
//        {
//            ex.printStackTrace();
//
//        }                              
//    }
//    
//    public String taoMatKhauMoi()
//    {
//        Date date = new Date();
//        long timeMilli = date.getTime();
//        return (timeMilli % 10000000)  + "";    
//    }
//    
//    public void clear()
//    {
//        taiKhoan_TF.setText("");
//        CMND_TF.setText("");
//        email_TF.setText("");
//    }
}
