/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlycafemangdi.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.JOptionPane;
import quanlycafemangdi.Util;
import quanlycafemangdi.model.CongThuc;
import quanlycafemangdi.model.NguyenLieu;
import quanlycafemangdi.model.SanPham;

/**
 *
 * @author admin
 */
public class SanPham_ThemFrame extends javax.swing.JFrame {

    private ArrayList<SanPham> danhSachSanPham;
    private ArrayList<CongThuc> danhSachCongThuc;
    private ArrayList<NguyenLieu> danhSachNguyenLieu;
    private ArrayList<String> danhSachMaSanPham = new ArrayList<>();
    
    private CongThuc congThuc = new CongThuc();
    
    private IOnFrameDispose onFrameDispose;
    
    private String buttonClicked = "";    
    private String loi;
    
    public SanPham_ThemFrame() {
        initComponents();       
        this.setLocationRelativeTo(null);
        
        layDonViTinh();
        layMaSanPham();
        
        maSanPham_TF.setText(taoMaSanPham());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        themSanPhamMoi_Lbl = new javax.swing.JLabel();
        maSanPham_Lbl = new javax.swing.JLabel();
        maSanPham_TF = new javax.swing.JTextField();
        tenSanPham_Lbl = new javax.swing.JLabel();
        tenSanPham_TF = new javax.swing.JTextField();
        donViTinh_Lbl = new javax.swing.JLabel();
        gia_Lbl = new javax.swing.JLabel();
        gia_TF = new javax.swing.JTextField();
        donViTinh_CBx = new javax.swing.JComboBox<>();
        congThuc_Lbl = new javax.swing.JLabel();
        chiTietCongThuc_Btn = new javax.swing.JButton();
        themSanPham_Btn = new javax.swing.JButton();
        huy_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm sản phẩm mới");
        setBackground(new java.awt.Color(255, 255, 255));

        themSanPhamMoi_Lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        themSanPhamMoi_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        themSanPhamMoi_Lbl.setText("Thêm sản phẩm mới");

        maSanPham_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maSanPham_Lbl.setText("Mã sản phẩm:");

        maSanPham_TF.setEditable(false);
        maSanPham_TF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maSanPham_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSanPham_TFActionPerformed(evt);
            }
        });

        tenSanPham_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tenSanPham_Lbl.setText("Tên sản phẩm:");

        tenSanPham_TF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        donViTinh_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        donViTinh_Lbl.setText("Đơn vị tính:");

        gia_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gia_Lbl.setText("Giá:");

        gia_TF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        donViTinh_CBx.setBackground(new java.awt.Color(254, 254, 254));
        donViTinh_CBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        congThuc_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        congThuc_Lbl.setText("Công thức:");

        chiTietCongThuc_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chiTietCongThuc_Btn.setText("Chi tiết công thức");
        chiTietCongThuc_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiTietCongThuc_BtnActionPerformed(evt);
            }
        });

        themSanPham_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        themSanPham_Btn.setText("Thêm ");
        themSanPham_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themSanPham_BtnActionPerformed(evt);
            }
        });

        huy_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        huy_Btn.setText("Hủy");
        huy_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huy_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(donViTinh_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(donViTinh_CBx, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(maSanPham_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(maSanPham_TF))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tenSanPham_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tenSanPham_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gia_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(congThuc_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(themSanPham_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(huy_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chiTietCongThuc_Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gia_TF))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(themSanPhamMoi_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(themSanPhamMoi_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maSanPham_Lbl)
                    .addComponent(maSanPham_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenSanPham_Lbl)
                    .addComponent(tenSanPham_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donViTinh_Lbl)
                    .addComponent(donViTinh_CBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gia_Lbl)
                    .addComponent(gia_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(congThuc_Lbl)
                    .addComponent(chiTietCongThuc_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(huy_Btn)
                    .addComponent(themSanPham_Btn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chiTietCongThuc_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiTietCongThuc_BtnActionPerformed
        SanPham_ChiTietCongThucDialog.setChucNang("Them");
        SanPham_ChiTietCongThucDialog sanPhamChiTietCongThucDialog = new SanPham_ChiTietCongThucDialog(this, rootPaneCheckingEnabled);
        sanPhamChiTietCongThucDialog.thietLapDuLieu(congThuc);
        sanPhamChiTietCongThucDialog.setVisible(true);
    }//GEN-LAST:event_chiTietCongThuc_BtnActionPerformed

    private void huy_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huy_BtnActionPerformed
        buttonClicked = "Huy";
        this.dispose();
    }//GEN-LAST:event_huy_BtnActionPerformed

    private void themSanPham_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themSanPham_BtnActionPerformed
        if (kiemTraLoi() == false)
        {
            themSanPham();
        }
    }//GEN-LAST:event_themSanPham_BtnActionPerformed

    private void maSanPham_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSanPham_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maSanPham_TFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPham_ThemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPham_ThemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPham_ThemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPham_ThemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPham_ThemFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chiTietCongThuc_Btn;
    private javax.swing.JLabel congThuc_Lbl;
    private javax.swing.JComboBox<String> donViTinh_CBx;
    private javax.swing.JLabel donViTinh_Lbl;
    private javax.swing.JLabel gia_Lbl;
    private javax.swing.JTextField gia_TF;
    private javax.swing.JButton huy_Btn;
    private javax.swing.JLabel maSanPham_Lbl;
    private javax.swing.JTextField maSanPham_TF;
    private javax.swing.JLabel tenSanPham_Lbl;
    private javax.swing.JTextField tenSanPham_TF;
    private javax.swing.JLabel themSanPhamMoi_Lbl;
    private javax.swing.JButton themSanPham_Btn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dispose() 
    {
        if (buttonClicked.equals("Huy"))
        {
            
            super.dispose();
        }
        else
        {
            onFrameDispose.onFrameDispose();
            super.dispose();
        }        
         //To change body of generated methods, choose Tools | Templates.
    }    
    
    public void layDonViTinh()
    {
        Connection connect = Util.getConnection();
        String query = "select * from DonViTinh";
        try
        {
            PreparedStatement ps = connect.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next())
            {
                donViTinh_CBx.addItem(rs.getString("tenDV"));
            }
        }catch (SQLException ex)
        {
            System.out.println("Lay don vi tinh len combo box that bai");
        }
    }    

    public String layMaDonVi(String donViTinh)
    {
        Connection connect = Util.getConnection();
        String query = "select * from DonViTinh where tenDV = '" + donViTinh + "'";
        try
        {
            PreparedStatement ps = connect.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            if (rs.next())
            {
                return rs.getString("maDV");
            }
        }catch (SQLException ex)
        {
            System.out.println("Lay ma don vi that bai");
        }
        return null;
    }     
    
    public String layMaSanPham()
    {
        Connection connect = Util.getConnection();
        String query = "select * from SanPham";
        try
        {
            PreparedStatement ps = connect.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next())
            {
                danhSachMaSanPham.add(rs.getString("maSP"));
            }
        }catch (SQLException ex)
        {
            System.out.println("Lay ma san pham that bai");
        }
        return null;        
    }
    
    public String taoMaSanPham()
    {
        int STT = 0;
        String maSanPham = "SP" + String.valueOf(STT);
        while (danhSachMaSanPham.contains(maSanPham))
        {
            STT++;
            maSanPham = "SP" + String.valueOf(STT);
        }
        return maSanPham;        
    }   
    
//    public boolean kiemTraMaSanPham(String maSanPham)
//    {
//        Connection connect = Util.getConnection();
//        String query = "select * from SanPham where SanPham.maSP = '" + maSanPham + "'";
//        try
//        {
//            PreparedStatement ps = connect.prepareStatement(query);
//            ResultSet rs = ps.executeQuery();
//            if (rs.next())
//            {
//                return false;
//            }
//        }catch (SQLException ex)
//        {
//            System.out.println("Kiem tra ma san pham that bai");
//        }
//        return true;
//    }    

    public boolean kiemTraLoi()
    {
        loi = "";
        
        String maSanPham = maSanPham_TF.getText();
        String gia = gia_TF.getText();
        
        if (maSanPham.equals(""))
        {
            loi = loi + "Mã sản phẩm không được để trống\n";
        }
//        else if (kiemTraMaSanPham(maSanPham) == false)
//        {
//            loi = loi + "Mã sản phẩm đã tồn tại\n";
//        }
        
        if (gia.equals(""))
        {
            loi = loi + "Giá tiền không được để trống\n";
        }
        else if (gia.matches("\\d+") == false)
        {
            loi = loi + "Giá tiền không hợp lệ\n";
        }
        
        if (congThuc.getChiTietCT().isEmpty() || congThuc.getCachLam().trim().equals(""))
        {
            loi = loi + "Vui lòng cho biết công thức pha chế\n";
        }
        
        if (loi.equals("") == false)
        {
            hienThiLoi(loi);
            return true;
        }
        else
        {
            return false;
        }
    }    
    
    public void hienThiLoi(String loi)
    {
        JOptionPane.showMessageDialog(rootPane, loi, "Lỗi", JOptionPane.ERROR_MESSAGE);
    }    
    
    public void themSanPham()
    {
        String maSanPham = maSanPham_TF.getText();
        String tenSanPham = tenSanPham_TF.getText();
        String donViTinh = (String) donViTinh_CBx.getSelectedItem();
        String maDonVi = layMaDonVi(donViTinh);
        String gia = gia_TF.getText();
        
        SanPham sanPham = new SanPham(maSanPham, tenSanPham, maDonVi, donViTinh, Long.parseLong(gia));
        danhSachSanPham.add(sanPham);        
        
        themSanPhamSQL(maSanPham, tenSanPham, maDonVi, Long.parseLong(gia), congThuc.getMaCT(), congThuc.getCachLam());
        congThuc.setMaSP(maSanPham); // Xu li loi sau khi them xong khong the xem cong thuc duoc ngay ma phai 
                                     //   restart chuong trinh. Nguyen nhan: Luc nay  khi tao xong cong thuc 
                                     //   ben dialog, cong thuc moi chi co maCT, maNL, soLuong va cachLam, van con thieu maSP
        danhSachCongThuc.add(congThuc);
        JOptionPane.showMessageDialog(rootPane, "Thêm sản phẩm mới thành công");
        this.dispose();
    }
    
    public void themSanPhamSQL(String maSanPham, String tenSanPham, String maDonVi, long gia, 
            String maCongThuc, String cachLam)
    {
        Connection connect = Util.getConnection();
        String query = "insert into SanPham values (?,?,?,?)"
                    +  " insert into CongThuc values (?,?,?)";
        String query2 = "insert into ChiTietCT values (?,?,?)";
        try
        {
            PreparedStatement ps = connect.prepareStatement(query);
            ps.setString(1, maSanPham);
            ps.setString(2, tenSanPham);
            ps.setString(3, maDonVi);
            ps.setLong(4, gia);
            ps.setString(5, maCongThuc);
            ps.setString(6, maSanPham);
            ps.setString(7, cachLam);
            ps.executeUpdate();
            
            ps = connect.prepareStatement(query2);
            Set<String> keySet = congThuc.getChiTietCT().keySet();
            for (String key: keySet)
            {
                ps.setString(1, maCongThuc);
                ps.setString(2, key);
                ps.setInt(3, congThuc.getChiTietCT().get(key));
                ps.executeUpdate();
            }
            ps.close();
            connect.close();
            
        }catch (SQLException ex)
        {
            System.out.println("Them san pham vao CSDL that bai");
        }
    }

    public void setOnFrameDispose(IOnFrameDispose onFrameDispose){
        this.onFrameDispose = onFrameDispose;
    } 
    
    public void setDanhSachCongThuc(ArrayList<CongThuc> danhSachCongThuc) {
        this.danhSachCongThuc = danhSachCongThuc;
    }

    public void setDanhSachNguyenLieu(ArrayList<NguyenLieu> danhSachNguyenLieu) {
        this.danhSachNguyenLieu = danhSachNguyenLieu;
    }
    
    public void setCongThuc(CongThuc congThuc) {
        this.congThuc = congThuc;
    }

    public void setDanhSachSanPham(ArrayList<SanPham> danhSachSanPham) {
        this.danhSachSanPham = danhSachSanPham;
    }    

    public ArrayList<NguyenLieu> getDanhSachNguyenLieu() {
        return danhSachNguyenLieu;
    }    
}

