/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlycafemangdi.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.JOptionPane;
import quanlycafemangdi.Util;
import quanlycafemangdi.model.CongThuc;
import quanlycafemangdi.model.NguyenLieu;
import quanlycafemangdi.model.SanPham;

/**
 *
 * @author admin
 */
public class SanPham_SuaFrame extends javax.swing.JFrame {

    private ArrayList<NguyenLieu> danhSachNguyenLieu;
    
    private SanPham sanPham;
    private CongThuc congThuc = new CongThuc();
    
    private IOnFrameDispose onFrameDispose;
    
    private String buttonClicked = "";
    private String loi;
    
    public SanPham_SuaFrame() {
        initComponents();
                
        this.setLocationRelativeTo(null);
        layDonViTinh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chinhSuaThongTinSanPham_Lbl = new javax.swing.JLabel();
        maSanPham_Lbl = new javax.swing.JLabel();
        maSanPham_TF = new javax.swing.JTextField();
        tenSanPham_Lbl = new javax.swing.JLabel();
        tenSanPham_TF = new javax.swing.JTextField();
        donViTinh_Lbl = new javax.swing.JLabel();
        gia_Lbl = new javax.swing.JLabel();
        gia_TF = new javax.swing.JTextField();
        donViTinh_CBx = new javax.swing.JComboBox<>();
        congThuc_Lbl = new javax.swing.JLabel();
        chiTietCongThuc_Btn = new javax.swing.JButton();
        sua_Btn = new javax.swing.JButton();
        huy_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        chinhSuaThongTinSanPham_Lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chinhSuaThongTinSanPham_Lbl.setText("Chỉnh sửa thông tin sản phẩm");

        maSanPham_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maSanPham_Lbl.setText("Mã sản phẩm:");

        maSanPham_TF.setEditable(false);
        maSanPham_TF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tenSanPham_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tenSanPham_Lbl.setText("Tên sản phẩm:");

        tenSanPham_TF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        donViTinh_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        donViTinh_Lbl.setText("Đơn vị tính:");

        gia_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gia_Lbl.setText("Giá:");

        gia_TF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        donViTinh_CBx.setBackground(new java.awt.Color(254, 254, 254));
        donViTinh_CBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        congThuc_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        congThuc_Lbl.setText("Công thức:");

        chiTietCongThuc_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chiTietCongThuc_Btn.setText("Chi tiết công thức");
        chiTietCongThuc_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiTietCongThuc_BtnActionPerformed(evt);
            }
        });

        sua_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sua_Btn.setText("Sửa");
        sua_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua_BtnActionPerformed(evt);
            }
        });

        huy_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        huy_Btn.setText("Hủy");
        huy_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huy_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(gia_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(congThuc_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chiTietCongThuc_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gia_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(tenSanPham_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tenSanPham_TF))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(maSanPham_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(maSanPham_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(sua_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(huy_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(donViTinh_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(donViTinh_CBx, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chinhSuaThongTinSanPham_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chinhSuaThongTinSanPham_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maSanPham_Lbl)
                    .addComponent(maSanPham_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenSanPham_Lbl)
                    .addComponent(tenSanPham_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donViTinh_Lbl)
                    .addComponent(donViTinh_CBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gia_Lbl)
                    .addComponent(gia_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(congThuc_Lbl)
                    .addComponent(chiTietCongThuc_Btn))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huy_Btn)
                    .addComponent(sua_Btn))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chiTietCongThuc_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiTietCongThuc_BtnActionPerformed
        SanPham_ChiTietCongThucDialog.setChucNang("ChinhSua");
        SanPham_ChiTietCongThucDialog sanPhamChiTietCongThucDialog = new SanPham_ChiTietCongThucDialog(this, rootPaneCheckingEnabled);
        sanPhamChiTietCongThucDialog.thietLapDuLieu(congThuc);
        //sanPhamChiTietCongThucDialog.setDanhSachNguyenLieu(danhSachNguyenLieu);
        sanPhamChiTietCongThucDialog.setVisible(true);
    }//GEN-LAST:event_chiTietCongThuc_BtnActionPerformed

    private void huy_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huy_BtnActionPerformed
        buttonClicked = "Huy";
        this.dispose();
    }//GEN-LAST:event_huy_BtnActionPerformed

    private void sua_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sua_BtnActionPerformed
        if (kiemTraLoi() == false)
        {
            suaSanPham();
        }
    }//GEN-LAST:event_sua_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPham_SuaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPham_SuaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPham_SuaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPham_SuaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPham_SuaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chiTietCongThuc_Btn;
    private javax.swing.JLabel chinhSuaThongTinSanPham_Lbl;
    private javax.swing.JLabel congThuc_Lbl;
    private javax.swing.JComboBox<String> donViTinh_CBx;
    private javax.swing.JLabel donViTinh_Lbl;
    private javax.swing.JLabel gia_Lbl;
    private javax.swing.JTextField gia_TF;
    private javax.swing.JButton huy_Btn;
    private javax.swing.JLabel maSanPham_Lbl;
    private javax.swing.JTextField maSanPham_TF;
    private javax.swing.JButton sua_Btn;
    private javax.swing.JLabel tenSanPham_Lbl;
    private javax.swing.JTextField tenSanPham_TF;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dispose() 
    {
        if (buttonClicked.equals("Huy"))
        {
            super.dispose();
        }
        else
        {
            onFrameDispose.onFrameDispose();
            super.dispose();
        }       
         //To change body of generated methods, choose Tools | Templates.
    }    
       
    public void thietLapDuLieu(SanPham sanPham, CongThuc congThuc)
    {
        this.sanPham = sanPham;
        this.congThuc = congThuc;
        
        maSanPham_TF.setText(sanPham.getMaSP());
        tenSanPham_TF.setText(sanPham.getTenSP());
        donViTinh_CBx.setSelectedItem(sanPham.getDonVi());
        gia_TF.setText(sanPham.getGia() + "");
        
    }
    
    public void layDonViTinh()
    {
        Connection connect = Util.getConnection();
        String query = "select * from DonViTinh";
        try
        {
            PreparedStatement ps = connect.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next())
            {
                donViTinh_CBx.addItem(rs.getString("tenDV"));
            }
        }catch (SQLException ex)
        {
            System.out.println("Lay don vi tinh len combo box that bai");
        }
    }    
    
    public String layMaDonVi(String donViTinh)
    {
        Connection connect = Util.getConnection();
        String query = "select * from DonViTinh where tenDV = '" + donViTinh + "'";
        try
        {
            PreparedStatement ps = connect.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            if (rs.next())
            {
                return rs.getString("maDV");
            }
        }catch (SQLException ex)
        {
            System.out.println("Lay ma don vi that bai");
        }
        return null;
    }     
          
    public void hienThiLoi(String loi)
    {
        JOptionPane.showMessageDialog(rootPane, loi, "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    
    public boolean kiemTraLoi()
    {
        loi = "";
        
        String gia = gia_TF.getText();
        
        if (gia.equals(""))
        {
            loi = loi + "Giá tiền không được để trống\n";
        }
        else if (gia.matches("\\d+") == false)
        {
            loi = loi + "Giá tiền không hợp lệ\n";
        }
        
        if (congThuc.getChiTietCT().isEmpty() || congThuc.getCachLam().trim().equals(""))
        {
            loi = loi + "Vui lòng cho biết công thức pha chế\n";
        }
        
        if (loi.equals("") == false)
        {
            hienThiLoi(loi);
            return true;
        }
        else
        {
            return false;
        }
    }
    
    public void suaSanPham()
    {
        String maSanPham = maSanPham_TF.getText();
        String tenSanPham = tenSanPham_TF.getText();
        String donViTinh = (String) donViTinh_CBx.getSelectedItem();
        String maDonVi = layMaDonVi(donViTinh);
        String gia = gia_TF.getText();
        
        sanPham.setTenSP(tenSanPham);
        sanPham.setDonVi(donViTinh);
        sanPham.setMaDonVi(maDonVi);
        sanPham.setGia(Long.parseLong(gia));
        
        suaSanPhamSQL(tenSanPham, maDonVi, Long.parseLong(gia), maSanPham, congThuc.getCachLam(), congThuc.getMaCT());
        JOptionPane.showMessageDialog(rootPane, "Hiệu chỉnh sản phẩm thành công");
        this.dispose();
    }
    
    public void suaSanPhamSQL(String tenSanPham, String maDonVi, long gia, String maSanPham, String cachLam, 
            String maCongThuc)
    {
        Connection connect = Util.getConnection();
        String query = "update SanPham set tenSP = ?, maDV = ?, gia = ? where maSP = '" + maSanPham + "'"
                    +  " update CongThuc set cachLam = ? where maCT = '" + maCongThuc + "'";
        try
        {
            PreparedStatement ps = connect.prepareStatement(query);
            ps.setString(1, tenSanPham);
            ps.setString(2, maDonVi);
            ps.setLong(3, gia);
            ps.setString(4, cachLam);
            ps.executeUpdate();
                        
            String query2 = "delete from ChiTietCT where maCT = '" + maCongThuc + "'";
            ps = connect.prepareStatement(query2);
            ps.executeUpdate();

            String query3 = "insert into ChiTietCT values (?,?,?)";
            ps = connect.prepareStatement(query3);           
            Set<String> keySet = congThuc.getChiTietCT().keySet();
            for (String key: keySet)
            {
                ps.setString(1, maCongThuc);
                ps.setString(2, key);
                ps.setInt(3, congThuc.getChiTietCT().get(key));
                ps.executeUpdate();
            }
            ps.close();
            connect.close();
        }catch (SQLException ex)
        {
            System.out.println("Sua san pham SQL that bai");
        }
    }

    public void setCongThuc(CongThuc congThuc) {
        this.congThuc = congThuc;
    }
 
    public void setOnFrameDispose(IOnFrameDispose onFrameDispose){
        this.onFrameDispose = onFrameDispose;
    }     
    
    public void setDanhSachNguyenLieu(ArrayList<NguyenLieu> danhSachNguyenLieu) {
        this.danhSachNguyenLieu = danhSachNguyenLieu;
    }    
    
    public ArrayList<NguyenLieu> getDanhSachNguyenLieu() {
        return danhSachNguyenLieu;
    }    
}
