/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlycafemangdi.view;

import quanlycafemangdi.Util;
import quanlycafemangdi.model.SanPham;

/**
 *
 * @author monar
 */
public class ThanhPhanHoaDonPanel extends javax.swing.JPanel {
    
    public static final int BAN_HANG = 0;
    public static final int DANG_KI = 1;
    
    
    private final SanPham sanPham;
    private int soLuong;
    private final int type;
    private IOnSpinnerStateChange onSpinnerStateChange;
    
    public interface IOnSpinnerStateChange{
        public void onStateChanged(SanPham sp, int sl, int type);
        public void onCancelButtonClicked(SanPham sp, int type);
        
    }

    /**
     * Creates new form ThanhPhanHoaDonPanel
     * @param sanPham
     * @param soLuong
     * @param onSpinnerStateChange
     */
    public ThanhPhanHoaDonPanel(SanPham sanPham, int soLuong,int type, IOnSpinnerStateChange onSpinnerStateChange) {
        initComponents();
        
        this.sanPham = sanPham;
        this.soLuong = soLuong;
        this.type = type;
        this.onSpinnerStateChange = onSpinnerStateChange;
        
        
        initData();
    }
    
    private void initData(){
        tenSP.setText(sanPham.getTenSP());
        capNhat(soLuong, sanPham.getGia());
    }
    private void capNhat(int sl, long gia){
        soLuongSn.setValue(sl);
        
        switch(type){
            case BAN_HANG -> {
                String giaTien = Util.formatCurrency(gia * sl);
                giaTienLb.setText(giaTien);
            }
            case DANG_KI -> {
                giaTienLb.setText("");
            }
            default -> {
                giaTienLb.setText("");
            }
        }
        
        
//        onSpinnerStateChange.onStateChanged(sanPham, sl);
//        onSpinnerStateChange.onAmountChange();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tenSP = new javax.swing.JLabel();
        giaTienLb = new javax.swing.JLabel();
        soLuongSn = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(450, 46));

        tenSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tenSP.setText("Cà phê đen");

        giaTienLb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        giaTienLb.setForeground(new java.awt.Color(255, 0, 0));
        giaTienLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        giaTienLb.setText("45,000");

        soLuongSn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        soLuongSn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                soLuongSnStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Số lượng");

        cancelBtn.setBackground(new java.awt.Color(32, 136, 203));
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/clear_white.png"))); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soLuongSn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(giaTienLb, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(soLuongSn)
                    .addComponent(giaTienLb)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void soLuongSnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_soLuongSnStateChanged
        // TODO add your handling code here:
        int value = (int)soLuongSn.getValue();
        if (value <= 0){
            value = 1;
            soLuongSn.setValue(value);
        }
        soLuong = (int)value;
        capNhat(value, sanPham.getGia());
        onSpinnerStateChange.onStateChanged(sanPham, value, type);
    }//GEN-LAST:event_soLuongSnStateChanged

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        onSpinnerStateChange.onCancelButtonClicked(sanPham,type);
        
    }//GEN-LAST:event_cancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel giaTienLb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner soLuongSn;
    private javax.swing.JLabel tenSP;
    // End of variables declaration//GEN-END:variables
}
