/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlycafemangdi.view;

import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import quanlycafemangdi.Util;
import quanlycafemangdi.model.ThongTinDangNhap;

/**
 *
 * @author admin
 */
public class TrangChu extends javax.swing.JFrame {
    
    private NhanVienPanel nhanVienPanel;
    private NguyenLieu_Panel nguyenLieuPanel;
    private Timer timer = new Timer(0, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date current = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            thoiGian_Lbl.setText(sdf.format(current));
        }
    });
    
    public TrangChu() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Hien thi o goc tren
        hienThiTenNguoiDung_Lbl.setText(ThongTinDangNhap.getTenDangNhap());
        hienThiChucVu_Lbl.setText(ThongTinDangNhap.getChucVu()); 
        
        // Thoi gian
        timer.start();
        
        // Hien thi o phan "Thong tin tai khoan" trong Tuy Chon
        hienThiThongTinTaiKhoan(ThongTinDangNhap.getTenDangNhap());
        
        nhanVienPanel = new NhanVienPanel(trangChu_LPn,trangChu_Pn);
        nguyenLieuPanel = new NguyenLieu_Panel(trangChu_LPn, trangChu_Pn);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nguoiDung_Lbl = new javax.swing.JLabel();
        chucVu_Lbl = new javax.swing.JLabel();
        hienThiTenNguoiDung_Lbl = new javax.swing.JLabel();
        hienThiChucVu_Lbl = new javax.swing.JLabel();
        thoiGian_Lbl = new javax.swing.JLabel();
        trangChu_LPn = new javax.swing.JLayeredPane();
        trangChu_Pn = new javax.swing.JPanel();
        cafe_Lbl = new javax.swing.JLabel();
        dangKiLichLam_Btn = new javax.swing.JButton();
        nguyenLieu_Btn = new javax.swing.JButton();
        sanPham_Btn = new javax.swing.JButton();
        diaDiemPhanCong_Btn = new javax.swing.JButton();
        tuyChon_Btn = new javax.swing.JButton();
        nhan_vien_btn = new javax.swing.JButton();
        dangXuat_Btn = new javax.swing.JButton();
        tuyChon_Pn = new javax.swing.JPanel();
        thongTinTaiKhoan_Btn = new javax.swing.JButton();
        doiMatKhau_Btn = new javax.swing.JButton();
        quayLai_Btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        tuyChon_Lbl = new javax.swing.JLabel();
        tinhNangCuaTuyChon_LPn = new javax.swing.JLayeredPane();
        thongTinTaiKhoan_Pn = new javax.swing.JPanel();
        thongTinTaiKhoan_Lbl = new javax.swing.JLabel();
        tenTaiKhoan_Lbl = new javax.swing.JLabel();
        tenTaiKhoan_TF = new javax.swing.JTextField();
        chucVu2_Lbl = new javax.swing.JLabel();
        chucVu2_TF = new javax.swing.JTextField();
        CMND_Lbl = new javax.swing.JLabel();
        CMND_TF = new javax.swing.JTextField();
        SDT_Lbl = new javax.swing.JLabel();
        SDT_TF = new javax.swing.JTextField();
        gioiTinh_Lbl = new javax.swing.JLabel();
        gioiTinh_TF = new javax.swing.JTextField();
        tenNhanVien_Lbl = new javax.swing.JLabel();
        tenNhanVien_TF = new javax.swing.JTextField();
        trangThai_Lbl = new javax.swing.JLabel();
        trangThai_TF = new javax.swing.JTextField();
        doiMatKhau_Pn = new javax.swing.JPanel();
        doiMatKhau_Lbl = new javax.swing.JLabel();
        matKhauCu_Lbl = new javax.swing.JLabel();
        matKhauCu_PwF = new javax.swing.JPasswordField();
        matKhauMoi_Lbl = new javax.swing.JLabel();
        matKhauMoi_PwF = new javax.swing.JPasswordField();
        nhapLaiMatKhauMoi_Lbl = new javax.swing.JLabel();
        nhapLaiMatKhauMoi_PwF = new javax.swing.JPasswordField();
        xacNhan_Btn = new javax.swing.JButton();
        huy_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        nguoiDung_Lbl.setText("Nguoi dung: ");

        chucVu_Lbl.setText("Chuc vu:");

        trangChu_LPn.setLayout(new java.awt.CardLayout());

        trangChu_Pn.setPreferredSize(new java.awt.Dimension(1000, 600));

        cafe_Lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cafe_Lbl.setText("Cafe 123");

        dangKiLichLam_Btn.setText("Dang ki lich lam");
        dangKiLichLam_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangKiLichLam_BtnActionPerformed(evt);
            }
        });

        nguyenLieu_Btn.setText("Nguyen lieu");
        nguyenLieu_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nguyenLieu_BtnActionPerformed(evt);
            }
        });

        sanPham_Btn.setText("San pham");

        diaDiemPhanCong_Btn.setText("Dia diem/Phan cong");

        tuyChon_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/ThietLap.png"))); // NOI18N
        tuyChon_Btn.setText("Tuy chon");
        tuyChon_Btn.setBorderPainted(false);
        tuyChon_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuyChon_BtnActionPerformed(evt);
            }
        });

        nhan_vien_btn.setText("Quản lý nhân viên");
        nhan_vien_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhan_vien_btnActionPerformed(evt);
            }
        });

        dangXuat_Btn.setText("Đăng xuất");
        dangXuat_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangXuat_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trangChu_PnLayout = new javax.swing.GroupLayout(trangChu_Pn);
        trangChu_Pn.setLayout(trangChu_PnLayout);
        trangChu_PnLayout.setHorizontalGroup(
            trangChu_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trangChu_PnLayout.createSequentialGroup()
                .addComponent(dangKiLichLam_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nguyenLieu_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sanPham_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(diaDiemPhanCong_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(trangChu_PnLayout.createSequentialGroup()
                .addGroup(trangChu_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trangChu_PnLayout.createSequentialGroup()
                        .addComponent(tuyChon_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dangXuat_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(trangChu_PnLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(nhan_vien_btn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trangChu_PnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cafe_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313))
        );
        trangChu_PnLayout.setVerticalGroup(
            trangChu_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChu_PnLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(cafe_Lbl)
                .addGap(28, 28, 28)
                .addGroup(trangChu_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dangKiLichLam_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nguyenLieu_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sanPham_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaDiemPhanCong_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(nhan_vien_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addGroup(trangChu_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tuyChon_Btn)
                    .addComponent(dangXuat_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        trangChu_LPn.add(trangChu_Pn, "card2");

        thongTinTaiKhoan_Btn.setText("Thong tin tai khoan");
        thongTinTaiKhoan_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongTinTaiKhoan_BtnActionPerformed(evt);
            }
        });

        doiMatKhau_Btn.setText("Doi mat khau");
        doiMatKhau_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doiMatKhau_BtnActionPerformed(evt);
            }
        });

        quayLai_Btn.setText("Quay lai");
        quayLai_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quayLai_BtnActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tuyChon_Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tuyChon_Lbl.setText("Tuy chon");

        tinhNangCuaTuyChon_LPn.setLayout(new java.awt.CardLayout());

        thongTinTaiKhoan_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thongTinTaiKhoan_Lbl.setText("Thong tin tai khoan");

        tenTaiKhoan_Lbl.setText("Ten tai khoan:");

        tenTaiKhoan_TF.setEditable(false);

        chucVu2_Lbl.setText("Chuc vu:");

        chucVu2_TF.setEditable(false);

        CMND_Lbl.setText("CMND:");

        CMND_TF.setEditable(false);
        CMND_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMND_TFActionPerformed(evt);
            }
        });

        SDT_Lbl.setText("SDT:");

        SDT_TF.setEditable(false);

        gioiTinh_Lbl.setText("Gioi tinh:");

        gioiTinh_TF.setEditable(false);

        tenNhanVien_Lbl.setText("Ten nhan vien:");

        tenNhanVien_TF.setEditable(false);

        trangThai_Lbl.setText("Trang thai:");

        trangThai_TF.setEditable(false);

        javax.swing.GroupLayout thongTinTaiKhoan_PnLayout = new javax.swing.GroupLayout(thongTinTaiKhoan_Pn);
        thongTinTaiKhoan_Pn.setLayout(thongTinTaiKhoan_PnLayout);
        thongTinTaiKhoan_PnLayout.setHorizontalGroup(
            thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thongTinTaiKhoan_PnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thongTinTaiKhoan_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(tenTaiKhoan_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenTaiKhoan_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(chucVu2_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chucVu2_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(CMND_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CMND_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(SDT_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDT_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(gioiTinh_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gioiTinh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(tenNhanVien_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenNhanVien_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(trangThai_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trangThai_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thongTinTaiKhoan_PnLayout.setVerticalGroup(
            thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thongTinTaiKhoan_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenTaiKhoan_Lbl)
                    .addComponent(tenTaiKhoan_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chucVu2_Lbl)
                    .addComponent(chucVu2_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMND_Lbl)
                    .addComponent(CMND_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SDT_Lbl)
                    .addComponent(SDT_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gioiTinh_Lbl)
                    .addComponent(gioiTinh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenNhanVien_Lbl)
                    .addComponent(tenNhanVien_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trangThai_Lbl)
                    .addComponent(trangThai_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        tinhNangCuaTuyChon_LPn.add(thongTinTaiKhoan_Pn, "card2");

        doiMatKhau_Pn.setPreferredSize(new java.awt.Dimension(368, 283));

        doiMatKhau_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doiMatKhau_Lbl.setText("Doi mat khau");

        matKhauCu_Lbl.setText("Mat khau cu:");

        matKhauCu_PwF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matKhauCu_PwFActionPerformed(evt);
            }
        });
        matKhauCu_PwF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matKhauCu_PwFKeyPressed(evt);
            }
        });

        matKhauMoi_Lbl.setText("Mat khau moi:");

        matKhauMoi_PwF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matKhauMoi_PwFKeyPressed(evt);
            }
        });

        nhapLaiMatKhauMoi_Lbl.setText("Nhap lai mat khau moi:");

        nhapLaiMatKhauMoi_PwF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nhapLaiMatKhauMoi_PwFKeyPressed(evt);
            }
        });

        xacNhan_Btn.setText("Xac nhan");
        xacNhan_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacNhan_BtnActionPerformed(evt);
            }
        });

        huy_Btn.setText("Huy");
        huy_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huy_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout doiMatKhau_PnLayout = new javax.swing.GroupLayout(doiMatKhau_Pn);
        doiMatKhau_Pn.setLayout(doiMatKhau_PnLayout);
        doiMatKhau_PnLayout.setHorizontalGroup(
            doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doiMatKhau_PnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doiMatKhau_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(doiMatKhau_PnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(matKhauMoi_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(matKhauCu_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nhapLaiMatKhauMoi_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matKhauCu_PwF)
                    .addComponent(matKhauMoi_PwF)
                    .addComponent(nhapLaiMatKhauMoi_PwF, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(doiMatKhau_PnLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(xacNhan_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(huy_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(537, Short.MAX_VALUE))
        );
        doiMatKhau_PnLayout.setVerticalGroup(
            doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doiMatKhau_PnLayout.createSequentialGroup()
                .addComponent(doiMatKhau_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matKhauCu_Lbl)
                    .addComponent(matKhauCu_PwF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matKhauMoi_Lbl)
                    .addComponent(matKhauMoi_PwF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhapLaiMatKhauMoi_Lbl)
                    .addComponent(nhapLaiMatKhauMoi_PwF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xacNhan_Btn)
                    .addComponent(huy_Btn))
                .addGap(0, 137, Short.MAX_VALUE))
        );

        tinhNangCuaTuyChon_LPn.add(doiMatKhau_Pn, "card3");

        javax.swing.GroupLayout tuyChon_PnLayout = new javax.swing.GroupLayout(tuyChon_Pn);
        tuyChon_Pn.setLayout(tuyChon_PnLayout);
        tuyChon_PnLayout.setHorizontalGroup(
            tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuyChon_PnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thongTinTaiKhoan_Btn)
                    .addComponent(doiMatKhau_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quayLai_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tinhNangCuaTuyChon_LPn)
                    .addGroup(tuyChon_PnLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(tuyChon_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        tuyChon_PnLayout.setVerticalGroup(
            tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuyChon_PnLayout.createSequentialGroup()
                .addComponent(tuyChon_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tuyChon_PnLayout.createSequentialGroup()
                        .addComponent(thongTinTaiKhoan_Btn)
                        .addGap(18, 18, 18)
                        .addComponent(doiMatKhau_Btn)
                        .addGap(18, 18, 18)
                        .addComponent(quayLai_Btn)
                        .addGap(107, 107, 107))
                    .addComponent(tinhNangCuaTuyChon_LPn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(tuyChon_PnLayout.createSequentialGroup()
                .addGap(0, 128, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        trangChu_LPn.add(tuyChon_Pn, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(chucVu_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nguoiDung_Lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hienThiTenNguoiDung_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hienThiChucVu_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thoiGian_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(trangChu_LPn, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hienThiTenNguoiDung_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nguoiDung_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thoiGian_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hienThiChucVu_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chucVu_Lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trangChu_LPn, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentAdded

    private void dangKiLichLam_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangKiLichLam_BtnActionPerformed

    }//GEN-LAST:event_dangKiLichLam_BtnActionPerformed

    private void tuyChon_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuyChon_BtnActionPerformed
        Util.doiPanel(trangChu_LPn,tuyChon_Pn);

    }//GEN-LAST:event_tuyChon_BtnActionPerformed

    private void thongTinTaiKhoan_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongTinTaiKhoan_BtnActionPerformed
       Util.doiPanel(tinhNangCuaTuyChon_LPn,thongTinTaiKhoan_Pn);
       
    }//GEN-LAST:event_thongTinTaiKhoan_BtnActionPerformed

    private void doiMatKhau_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doiMatKhau_BtnActionPerformed
        Util.doiPanel(tinhNangCuaTuyChon_LPn,doiMatKhau_Pn);
    }//GEN-LAST:event_doiMatKhau_BtnActionPerformed

    private void quayLai_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quayLai_BtnActionPerformed
        Util.doiPanel(trangChu_LPn,trangChu_Pn); // 
    }//GEN-LAST:event_quayLai_BtnActionPerformed

    private void CMND_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMND_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMND_TFActionPerformed

    private void huy_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huy_BtnActionPerformed
        matKhauCu_PwF.setText("");
        matKhauMoi_PwF.setText("");
        nhapLaiMatKhauMoi_PwF.setText("");
    }//GEN-LAST:event_huy_BtnActionPerformed

    private void xacNhan_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacNhan_BtnActionPerformed
        xacNhanDoiMatKhau();
    }//GEN-LAST:event_xacNhan_BtnActionPerformed

    private void nhan_vien_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhan_vien_btnActionPerformed
        // TODO add your handling code here:
        Util.doiPanel(trangChu_LPn, nhanVienPanel);
    }//GEN-LAST:event_nhan_vien_btnActionPerformed

    private void matKhauCu_PwFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matKhauCu_PwFKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            xacNhanDoiMatKhau();
        }
    }//GEN-LAST:event_matKhauCu_PwFKeyPressed

    private void matKhauMoi_PwFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matKhauMoi_PwFKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            xacNhanDoiMatKhau();
        }
    }//GEN-LAST:event_matKhauMoi_PwFKeyPressed

    private void nhapLaiMatKhauMoi_PwFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nhapLaiMatKhauMoi_PwFKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            xacNhanDoiMatKhau();
        }
    }//GEN-LAST:event_nhapLaiMatKhauMoi_PwFKeyPressed

    private void nguyenLieu_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nguyenLieu_BtnActionPerformed
        Util.doiPanel(trangChu_LPn, nguyenLieuPanel);
    }//GEN-LAST:event_nguyenLieu_BtnActionPerformed

    private void dangXuat_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangXuat_BtnActionPerformed
        int luaChon = JOptionPane.showConfirmDialog(rootPane, "Dang xuat?", "Thoat", JOptionPane.YES_NO_OPTION);
        if (luaChon == JOptionPane.YES_OPTION)
        {
            this.dispose();
            DangNhap dangNhap = new DangNhap();
            dangNhap.setVisible(true);            
        }
        else
        {
            
        }
    }//GEN-LAST:event_dangXuat_BtnActionPerformed

    private void matKhauCu_PwFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matKhauCu_PwFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matKhauCu_PwFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CMND_Lbl;
    private javax.swing.JTextField CMND_TF;
    private javax.swing.JLabel SDT_Lbl;
    private javax.swing.JTextField SDT_TF;
    private javax.swing.JLabel cafe_Lbl;
    private javax.swing.JLabel chucVu2_Lbl;
    private javax.swing.JTextField chucVu2_TF;
    private javax.swing.JLabel chucVu_Lbl;
    private javax.swing.JButton dangKiLichLam_Btn;
    private javax.swing.JButton dangXuat_Btn;
    private javax.swing.JButton diaDiemPhanCong_Btn;
    private javax.swing.JButton doiMatKhau_Btn;
    private javax.swing.JLabel doiMatKhau_Lbl;
    private javax.swing.JPanel doiMatKhau_Pn;
    private javax.swing.JLabel gioiTinh_Lbl;
    private javax.swing.JTextField gioiTinh_TF;
    private javax.swing.JLabel hienThiChucVu_Lbl;
    private javax.swing.JLabel hienThiTenNguoiDung_Lbl;
    private javax.swing.JButton huy_Btn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel matKhauCu_Lbl;
    private javax.swing.JPasswordField matKhauCu_PwF;
    private javax.swing.JLabel matKhauMoi_Lbl;
    private javax.swing.JPasswordField matKhauMoi_PwF;
    private javax.swing.JLabel nguoiDung_Lbl;
    private javax.swing.JButton nguyenLieu_Btn;
    private javax.swing.JButton nhan_vien_btn;
    private javax.swing.JLabel nhapLaiMatKhauMoi_Lbl;
    private javax.swing.JPasswordField nhapLaiMatKhauMoi_PwF;
    private javax.swing.JButton quayLai_Btn;
    private javax.swing.JButton sanPham_Btn;
    private javax.swing.JLabel tenNhanVien_Lbl;
    private javax.swing.JTextField tenNhanVien_TF;
    private javax.swing.JLabel tenTaiKhoan_Lbl;
    private javax.swing.JTextField tenTaiKhoan_TF;
    private javax.swing.JLabel thoiGian_Lbl;
    private javax.swing.JButton thongTinTaiKhoan_Btn;
    private javax.swing.JLabel thongTinTaiKhoan_Lbl;
    private javax.swing.JPanel thongTinTaiKhoan_Pn;
    private javax.swing.JLayeredPane tinhNangCuaTuyChon_LPn;
    private javax.swing.JLayeredPane trangChu_LPn;
    private javax.swing.JPanel trangChu_Pn;
    private javax.swing.JLabel trangThai_Lbl;
    private javax.swing.JTextField trangThai_TF;
    private javax.swing.JButton tuyChon_Btn;
    private javax.swing.JLabel tuyChon_Lbl;
    private javax.swing.JPanel tuyChon_Pn;
    private javax.swing.JButton xacNhan_Btn;
    // End of variables declaration//GEN-END:variables

     
    
    
    public void hienThiThongTinTaiKhoan(String tenDangNhap)
    {
        String query = "select * from NhanVien where tenTK = '" + tenDangNhap + "'";
        try
        {
            Connection connect = Util.getConnection();
            PreparedStatement ps = connect.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            if (rs.next())
            {
                tenTaiKhoan_TF.setText(rs.getString("tenTK"));
                chucVu2_TF.setText(rs.getString("chucVu"));
                CMND_TF.setText(rs.getString("CMND"));
                SDT_TF.setText(rs.getString("SDT"));
                gioiTinh_TF.setText(rs.getString("gioiTinh"));
                tenNhanVien_TF.setText(rs.getString("tenNV"));
                trangThai_TF.setText(rs.getString("trangThai"));
                rs.close();
                ps.close();
                connect.close();
            }
        }catch (SQLException ex)
        {
            System.out.println("Hien thi thong tin tai khoan that bai");
        }
    }
    
    public void doiMatKhau(String tenDangNhap, String matKhau)
    {
        String query = "update NhanVien set matKhau = ? where tenTK = '" + tenDangNhap + "'";
        try
        {
            Connection connect = Util.getConnection();
            PreparedStatement ps = connect.prepareStatement(query);
            ps.setString(1, matKhau);
            ps.executeUpdate();
            ps.close();
            connect.close();
        }catch (SQLException ex)
        {
            System.out.println("Doi mat khau that bai");
        }
    }
    
    public void xacNhanDoiMatKhau()
    {
        String matKhauCu = matKhauCu_PwF.getText();
        String matKhauMoi = matKhauMoi_PwF.getText();
        String nhapLaiMatKhauMoi = nhapLaiMatKhauMoi_PwF.getText();
        
        boolean trongMatKhauCu = false, trongMatKhauMoi = false, trongNhapLaiMatKhauMoi = false;
        if (matKhauCu.equals(""))
        {
            trongMatKhauCu = true;
            JOptionPane.showMessageDialog(rootPane, "Vui long nhap day du thong tin.", "Loi",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if (matKhauMoi.equals(""))
        {
            trongMatKhauMoi = true;
            JOptionPane.showMessageDialog(rootPane, "Vui long nhap day du thong tin.", "Loi",
                    JOptionPane.ERROR_MESSAGE);
        }        
        else if (nhapLaiMatKhauMoi.equals(""))
        {
            trongNhapLaiMatKhauMoi = true;
            JOptionPane.showMessageDialog(rootPane, "Vui long nhap day du thong tin.", "Loi",
                    JOptionPane.ERROR_MESSAGE);
        }        
        else
        {
            if (matKhauCu.equals(ThongTinDangNhap.getMatKhau()) == false)
            {
                JOptionPane.showMessageDialog(rootPane, "Mat khau cu khong chinh xac.", "Loi",
                        JOptionPane.ERROR_MESSAGE);
            }
            else if (matKhauMoi.equals(nhapLaiMatKhauMoi) == false)
            {
                JOptionPane.showMessageDialog(rootPane, "Mat khau moi khong khong trung khop.", "Loi",
                        JOptionPane.ERROR_MESSAGE);                
            }
            else
            {
                doiMatKhau(ThongTinDangNhap.getTenDangNhap(), matKhauMoi);
                JOptionPane.showMessageDialog(rootPane, "Doi mat khau thanh cong");                
            }
        }        
    }
        
}
