package quanlycafemangdi.view;

import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import quanlycafemangdi.Util;
import quanlycafemangdi.model.ThongTinDangNhap;

/**
 *
 * @author admin
 */
public class TrangChu extends javax.swing.JFrame {
    
    private NhanVienPanel nhanVienPanel;
    private BanHangPanel banHangPanel;
    private NguyenLieu_Panel nguyenLieuPanel;
    private ThongKePanel thongKePanel;
    Timer timer = new Timer(0, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date current = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
            thoiGian_Lbl.setText(sdf.format(current));
        }
    });
    
    public TrangChu() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Hien thi o goc tren
        hienThiTenNguoiDung_Lbl.setText(ThongTinDangNhap.getTenNguoiDung());
        ngay_Lbl.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date())); 
        
        // Thoi gian
        timer.start();
        
        // Hien thi o phan "Thong tin tai khoan" trong Tuy Chon
        hienThiThongTinTaiKhoan(ThongTinDangNhap.getTenDangNhap());
        
        nhanVienPanel = new NhanVienPanel();
        banHangPanel = new BanHangPanel();
        nguyenLieuPanel = new NguyenLieu_Panel(trangChu_LPn, trangChu_Pn);
        thongKePanel = new ThongKePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        hienThiTenNguoiDung_Lbl = new javax.swing.JLabel();
        ngay_Lbl = new javax.swing.JLabel();
        thoiGian_Lbl = new javax.swing.JLabel();
        trangChu_LPn = new javax.swing.JLayeredPane();
        trangChu_Pn = new javax.swing.JPanel();
        cafe_Lbl = new javax.swing.JLabel();
        dangKiLichLam_Btn = new javax.swing.JButton();
        nguyenLieu_Btn = new javax.swing.JButton();
        sanPham_Btn = new javax.swing.JButton();
        diaDiemPhanCong_Btn = new javax.swing.JButton();
        tuyChon_Btn = new javax.swing.JButton();
        nhan_vien_btn = new javax.swing.JButton();
        banHangBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tuyChon_Pn = new javax.swing.JPanel();
        thongTinTaiKhoan_Btn = new javax.swing.JButton();
        doiMatKhau_Btn = new javax.swing.JButton();
        quayLai_Btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        tuyChon_Lbl = new javax.swing.JLabel();
        tinhNangCuaTuyChon_LPn = new javax.swing.JLayeredPane();
        thongTinTaiKhoan_Pn = new javax.swing.JPanel();
        thongTinTaiKhoan_Lbl = new javax.swing.JLabel();
        tenTaiKhoan_Lbl = new javax.swing.JLabel();
        tenTaiKhoan_TF = new javax.swing.JTextField();
        chucVu2_Lbl = new javax.swing.JLabel();
        chucVu2_TF = new javax.swing.JTextField();
        CMND_Lbl = new javax.swing.JLabel();
        CMND_TF = new javax.swing.JTextField();
        SDT_Lbl = new javax.swing.JLabel();
        SDT_TF = new javax.swing.JTextField();
        gioiTinh_Lbl = new javax.swing.JLabel();
        gioiTinh_TF = new javax.swing.JTextField();
        tenNhanVien_Lbl = new javax.swing.JLabel();
        tenNhanVien_TF = new javax.swing.JTextField();
        trangThai_Lbl = new javax.swing.JLabel();
        trangThai_TF = new javax.swing.JTextField();
        doiMatKhau_Pn = new javax.swing.JPanel();
        doiMatKhau_Lbl = new javax.swing.JLabel();
        matKhauCu_Lbl = new javax.swing.JLabel();
        matKhauCu_PwF = new javax.swing.JPasswordField();
        matKhauMoi_Lbl = new javax.swing.JLabel();
        matKhauMoi_PwF = new javax.swing.JPasswordField();
        nhapLaiMatKhauMoi_Lbl = new javax.swing.JLabel();
        nhapLaiMatKhauMoi_PwF = new javax.swing.JPasswordField();
        xacNhan_Btn = new javax.swing.JButton();
        huy_Btn = new javax.swing.JButton();
        chucNangLayeredPane = new javax.swing.JLayeredPane();
        quanLyPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        hienThiTenNguoiDung_Lbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hienThiTenNguoiDung_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hienThiTenNguoiDung_Lbl.setText("887687hjhj");

        ngay_Lbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ngay_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ngay_Lbl.setText("sdfsdfsdf");

        thoiGian_Lbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        thoiGian_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thoiGian_Lbl.setText("sdadsa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienThiTenNguoiDung_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
            .addComponent(ngay_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(thoiGian_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(hienThiTenNguoiDung_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ngay_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thoiGian_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        trangChu_LPn.setLayout(new java.awt.CardLayout());

        trangChu_Pn.setPreferredSize(new java.awt.Dimension(1000, 700));

        cafe_Lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cafe_Lbl.setText("Cafe 123");

        dangKiLichLam_Btn.setText("Dang ki lich lam");
        dangKiLichLam_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangKiLichLam_BtnActionPerformed(evt);
            }
        });

        nguyenLieu_Btn.setText("Nguyen lieu");
        nguyenLieu_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nguyenLieu_BtnActionPerformed(evt);
            }
        });

        sanPham_Btn.setText("San pham");

        diaDiemPhanCong_Btn.setText("Dia diem/Phan cong");

        tuyChon_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/ThietLap.png"))); // NOI18N
        tuyChon_Btn.setText("Tuy chon");
        tuyChon_Btn.setBorderPainted(false);
        tuyChon_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuyChon_BtnActionPerformed(evt);
            }
        });

        nhan_vien_btn.setText("Quản lý nhân viên");
        nhan_vien_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhan_vien_btnActionPerformed(evt);
            }
        });

        banHangBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        banHangBtn.setText("Bán hàng");
        banHangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banHangBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Đăng xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trangChu_PnLayout = new javax.swing.GroupLayout(trangChu_Pn);
        trangChu_Pn.setLayout(trangChu_PnLayout);
        trangChu_PnLayout.setHorizontalGroup(
            trangChu_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trangChu_PnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cafe_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trangChu_PnLayout.createSequentialGroup()
                .addComponent(dangKiLichLam_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(nguyenLieu_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sanPham_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diaDiemPhanCong_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(trangChu_PnLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(nhan_vien_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(banHangBtn)
                .addContainerGap(662, Short.MAX_VALUE))
            .addGroup(trangChu_PnLayout.createSequentialGroup()
                .addComponent(tuyChon_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        trangChu_PnLayout.setVerticalGroup(
            trangChu_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChu_PnLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(cafe_Lbl)
                .addGap(36, 36, 36)
                .addGroup(trangChu_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dangKiLichLam_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nguyenLieu_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sanPham_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaDiemPhanCong_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(trangChu_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhan_vien_btn)
                    .addComponent(banHangBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addGroup(trangChu_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(trangChu_PnLayout.createSequentialGroup()
                        .addComponent(tuyChon_Btn)
                        .addContainerGap())
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        trangChu_LPn.add(trangChu_Pn, "card2");

        thongTinTaiKhoan_Btn.setText("Thong tin tai khoan");
        thongTinTaiKhoan_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongTinTaiKhoan_BtnActionPerformed(evt);
            }
        });

        doiMatKhau_Btn.setText("Doi mat khau");
        doiMatKhau_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doiMatKhau_BtnActionPerformed(evt);
            }
        });

        quayLai_Btn.setText("Quay lai");
        quayLai_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quayLai_BtnActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tuyChon_Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tuyChon_Lbl.setText("Tuy chon");

        tinhNangCuaTuyChon_LPn.setLayout(new java.awt.CardLayout());

        thongTinTaiKhoan_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thongTinTaiKhoan_Lbl.setText("Thong tin tai khoan");

        tenTaiKhoan_Lbl.setText("Ten tai khoan:");

        tenTaiKhoan_TF.setEditable(false);

        chucVu2_Lbl.setText("Chuc vu:");

        chucVu2_TF.setEditable(false);

        CMND_Lbl.setText("CMND:");

        CMND_TF.setEditable(false);
        CMND_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMND_TFActionPerformed(evt);
            }
        });

        SDT_Lbl.setText("SDT:");

        SDT_TF.setEditable(false);

        gioiTinh_Lbl.setText("Gioi tinh:");

        gioiTinh_TF.setEditable(false);

        tenNhanVien_Lbl.setText("Ten nhan vien:");

        tenNhanVien_TF.setEditable(false);

        trangThai_Lbl.setText("Trang thai:");

        trangThai_TF.setEditable(false);

        javax.swing.GroupLayout thongTinTaiKhoan_PnLayout = new javax.swing.GroupLayout(thongTinTaiKhoan_Pn);
        thongTinTaiKhoan_Pn.setLayout(thongTinTaiKhoan_PnLayout);
        thongTinTaiKhoan_PnLayout.setHorizontalGroup(
            thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thongTinTaiKhoan_PnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thongTinTaiKhoan_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(tenTaiKhoan_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenTaiKhoan_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(chucVu2_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chucVu2_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(CMND_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CMND_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(SDT_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDT_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(gioiTinh_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gioiTinh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(tenNhanVien_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenNhanVien_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                        .addComponent(trangThai_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trangThai_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thongTinTaiKhoan_PnLayout.setVerticalGroup(
            thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongTinTaiKhoan_PnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thongTinTaiKhoan_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenTaiKhoan_Lbl)
                    .addComponent(tenTaiKhoan_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chucVu2_Lbl)
                    .addComponent(chucVu2_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMND_Lbl)
                    .addComponent(CMND_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SDT_Lbl)
                    .addComponent(SDT_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gioiTinh_Lbl)
                    .addComponent(gioiTinh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenNhanVien_Lbl)
                    .addComponent(tenNhanVien_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thongTinTaiKhoan_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trangThai_Lbl)
                    .addComponent(trangThai_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        tinhNangCuaTuyChon_LPn.add(thongTinTaiKhoan_Pn, "card2");

        doiMatKhau_Pn.setPreferredSize(new java.awt.Dimension(368, 283));

        doiMatKhau_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doiMatKhau_Lbl.setText("Doi mat khau");

        matKhauCu_Lbl.setText("Mat khau cu:");

        matKhauMoi_Lbl.setText("Mat khau moi:");

        nhapLaiMatKhauMoi_Lbl.setText("Nhap lai mat khau moi:");

        xacNhan_Btn.setText("Xac nhan");
        xacNhan_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacNhan_BtnActionPerformed(evt);
            }
        });

        huy_Btn.setText("Huy");
        huy_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huy_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout doiMatKhau_PnLayout = new javax.swing.GroupLayout(doiMatKhau_Pn);
        doiMatKhau_Pn.setLayout(doiMatKhau_PnLayout);
        doiMatKhau_PnLayout.setHorizontalGroup(
            doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doiMatKhau_PnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doiMatKhau_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(doiMatKhau_PnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(matKhauMoi_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(matKhauCu_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nhapLaiMatKhauMoi_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matKhauCu_PwF)
                    .addComponent(matKhauMoi_PwF)
                    .addComponent(nhapLaiMatKhauMoi_PwF, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(doiMatKhau_PnLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(xacNhan_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(huy_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        doiMatKhau_PnLayout.setVerticalGroup(
            doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doiMatKhau_PnLayout.createSequentialGroup()
                .addComponent(doiMatKhau_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matKhauCu_Lbl)
                    .addComponent(matKhauCu_PwF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matKhauMoi_Lbl)
                    .addComponent(matKhauMoi_PwF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhapLaiMatKhauMoi_Lbl)
                    .addComponent(nhapLaiMatKhauMoi_PwF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(doiMatKhau_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xacNhan_Btn)
                    .addComponent(huy_Btn))
                .addGap(0, 137, Short.MAX_VALUE))
        );

        tinhNangCuaTuyChon_LPn.add(doiMatKhau_Pn, "card3");

        javax.swing.GroupLayout tuyChon_PnLayout = new javax.swing.GroupLayout(tuyChon_Pn);
        tuyChon_Pn.setLayout(tuyChon_PnLayout);
        tuyChon_PnLayout.setHorizontalGroup(
            tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuyChon_PnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thongTinTaiKhoan_Btn)
                    .addComponent(doiMatKhau_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quayLai_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tinhNangCuaTuyChon_LPn)
                    .addGroup(tuyChon_PnLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(tuyChon_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        tuyChon_PnLayout.setVerticalGroup(
            tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuyChon_PnLayout.createSequentialGroup()
                .addComponent(tuyChon_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tuyChon_PnLayout.createSequentialGroup()
                        .addComponent(thongTinTaiKhoan_Btn)
                        .addGap(18, 18, 18)
                        .addComponent(doiMatKhau_Btn)
                        .addGap(18, 18, 18)
                        .addComponent(quayLai_Btn)
                        .addGap(107, 107, 107))
                    .addComponent(tinhNangCuaTuyChon_LPn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(tuyChon_PnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        trangChu_LPn.add(tuyChon_Pn, "card3");

        chucNangLayeredPane.setLayout(new java.awt.CardLayout());

        quanLyPanel.setPreferredSize(new java.awt.Dimension(30, 535));
        quanLyPanel.setLayout(new javax.swing.BoxLayout(quanLyPanel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(72, 30));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/trangChu.png"))); // NOI18N
        jLabel1.setText("Trang chủ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        quanLyPanel.add(jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setPreferredSize(new java.awt.Dimension(72, 24));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/nguyenLieu.png"))); // NOI18N
        jLabel3.setText("Quản lý kho");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        quanLyPanel.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel5.setPreferredSize(new java.awt.Dimension(72, 24));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/sanPham.png"))); // NOI18N
        jLabel4.setText("Sản phẩm");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        quanLyPanel.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel6.setPreferredSize(new java.awt.Dimension(72, 24));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/nhanVien.png"))); // NOI18N
        jLabel5.setText("Nhân viên");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        quanLyPanel.add(jPanel6);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel8.setPreferredSize(new java.awt.Dimension(72, 24));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/diaDiem.png"))); // NOI18N
        jLabel7.setText("Địa điểm");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        quanLyPanel.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel9.setPreferredSize(new java.awt.Dimension(72, 24));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/banHang.png"))); // NOI18N
        jLabel8.setText("Bán hàng");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        quanLyPanel.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel10.setPreferredSize(new java.awt.Dimension(72, 24));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/thongKe.png"))); // NOI18N
        jLabel9.setText("Thống kê");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        quanLyPanel.add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel11.setPreferredSize(new java.awt.Dimension(72, 24));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/ThietLap.png"))); // NOI18N
        jLabel10.setText("Tùy chọn");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        quanLyPanel.add(jPanel11);

        chucNangLayeredPane.add(quanLyPanel, "card2");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chucNangLayeredPane)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trangChu_LPn, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chucNangLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(trangChu_LPn, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentAdded

    private void dangKiLichLam_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangKiLichLam_BtnActionPerformed

    }//GEN-LAST:event_dangKiLichLam_BtnActionPerformed

    private void tuyChon_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuyChon_BtnActionPerformed
        Util.doiPanel(trangChu_LPn,tuyChon_Pn);

    }//GEN-LAST:event_tuyChon_BtnActionPerformed

    private void thongTinTaiKhoan_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongTinTaiKhoan_BtnActionPerformed
       Util.doiPanel(tinhNangCuaTuyChon_LPn,thongTinTaiKhoan_Pn);
       
    }//GEN-LAST:event_thongTinTaiKhoan_BtnActionPerformed

    private void doiMatKhau_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doiMatKhau_BtnActionPerformed
        Util.doiPanel(tinhNangCuaTuyChon_LPn,doiMatKhau_Pn);
    }//GEN-LAST:event_doiMatKhau_BtnActionPerformed

    private void quayLai_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quayLai_BtnActionPerformed
        Util.doiPanel(trangChu_LPn,trangChu_Pn); // 
    }//GEN-LAST:event_quayLai_BtnActionPerformed

    private void CMND_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMND_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMND_TFActionPerformed

    private void huy_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huy_BtnActionPerformed
        matKhauCu_PwF.setText("");
        matKhauMoi_PwF.setText("");
        nhapLaiMatKhauMoi_PwF.setText("");
    }//GEN-LAST:event_huy_BtnActionPerformed

    private void xacNhan_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacNhan_BtnActionPerformed
        String matKhauCu = matKhauCu_PwF.getText();
        String matKhauMoi = matKhauMoi_PwF.getText();
        String nhapLaiMatKhauMoi = nhapLaiMatKhauMoi_PwF.getText();
        
        boolean trongMatKhauCu = false, trongMatKhauMoi = false, trongNhapLaiMatKhauMoi = false;
        if (matKhauCu.equals(""))
        {
            trongMatKhauCu = true;
            JOptionPane.showMessageDialog(rootPane, "Vui long nhap day du thong tin.", "Loi",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if (matKhauMoi.equals(""))
        {
            trongMatKhauMoi = true;
            JOptionPane.showMessageDialog(rootPane, "Vui long nhap day du thong tin.", "Loi",
                    JOptionPane.ERROR_MESSAGE);
        }        
        else if (nhapLaiMatKhauMoi.equals(""))
        {
            trongNhapLaiMatKhauMoi = true;
            JOptionPane.showMessageDialog(rootPane, "Vui long nhap day du thong tin.", "Loi",
                    JOptionPane.ERROR_MESSAGE);
        }        
        else
        {
//            if (matKhauCu.equals(ThongTinDangNhap.getMatKhau()) == false )
//            {
//                JOptionPane.showMessageDialog(rootPane, "Mat khau cu khong chinh xac.", "Loi", 
//                        JOptionPane.ERROR_MESSAGE);     
//            }
//            else if (matKhauMoi.equals(nhapLaiMatKhauMoi) == false)
//            {
//                JOptionPane.showMessageDialog(rootPane, "Mat khau moi va mat khau nhap lai khong trung khop.", "Loi", 
//                        JOptionPane.ERROR_MESSAGE);
//            }
//            else
//            {
                doiMatKhau(ThongTinDangNhap.getTenDangNhap(), ThongTinDangNhap.getMatKhau());
                JOptionPane.showMessageDialog(rootPane, "Doi mat khau thanh cong");
//            }
        }
    }//GEN-LAST:event_xacNhan_BtnActionPerformed

    private void nhan_vien_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhan_vien_btnActionPerformed
        // TODO add your handling code here:
        Util.doiPanel(trangChu_LPn, nhanVienPanel);
//        Util.doiPanel(trangChu_LPn, banHangPanel);
    }//GEN-LAST:event_nhan_vien_btnActionPerformed

    private void banHangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banHangBtnActionPerformed
        // TODO add your handling code here:
        Util.doiPanel(trangChu_LPn, banHangPanel);
    }//GEN-LAST:event_banHangBtnActionPerformed

    private void nguyenLieu_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nguyenLieu_BtnActionPerformed
        Util.doiPanel(trangChu_LPn, nguyenLieuPanel);
    }//GEN-LAST:event_nguyenLieu_BtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int luaChon = JOptionPane.showConfirmDialog(rootPane, "Dang xuat?", "Thoat", JOptionPane.YES_NO_OPTION);
        if (luaChon == JOptionPane.YES_OPTION)
        {
            this.dispose();
            DangNhap dangNhap = new DangNhap();
            dangNhap.setVisible(true);            
        }
        else
        {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        Util.doiPanel(trangChu_LPn, trangChu_Pn);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        Util.doiPanel(trangChu_LPn, nhanVienPanel);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
        Util.doiPanel(trangChu_LPn, banHangPanel);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Util.doiPanel(trangChu_LPn, thongKePanel);
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CMND_Lbl;
    private javax.swing.JTextField CMND_TF;
    private javax.swing.JLabel SDT_Lbl;
    private javax.swing.JTextField SDT_TF;
    private javax.swing.JButton banHangBtn;
    private javax.swing.JLabel cafe_Lbl;
    private javax.swing.JLayeredPane chucNangLayeredPane;
    private javax.swing.JLabel chucVu2_Lbl;
    private javax.swing.JTextField chucVu2_TF;
    private javax.swing.JButton dangKiLichLam_Btn;
    private javax.swing.JButton diaDiemPhanCong_Btn;
    private javax.swing.JButton doiMatKhau_Btn;
    private javax.swing.JLabel doiMatKhau_Lbl;
    private javax.swing.JPanel doiMatKhau_Pn;
    private javax.swing.JLabel gioiTinh_Lbl;
    private javax.swing.JTextField gioiTinh_TF;
    private javax.swing.JLabel hienThiTenNguoiDung_Lbl;
    private javax.swing.JButton huy_Btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel matKhauCu_Lbl;
    private javax.swing.JPasswordField matKhauCu_PwF;
    private javax.swing.JLabel matKhauMoi_Lbl;
    private javax.swing.JPasswordField matKhauMoi_PwF;
    private javax.swing.JLabel ngay_Lbl;
    private javax.swing.JButton nguyenLieu_Btn;
    private javax.swing.JButton nhan_vien_btn;
    private javax.swing.JLabel nhapLaiMatKhauMoi_Lbl;
    private javax.swing.JPasswordField nhapLaiMatKhauMoi_PwF;
    private javax.swing.JPanel quanLyPanel;
    private javax.swing.JButton quayLai_Btn;
    private javax.swing.JButton sanPham_Btn;
    private javax.swing.JLabel tenNhanVien_Lbl;
    private javax.swing.JTextField tenNhanVien_TF;
    private javax.swing.JLabel tenTaiKhoan_Lbl;
    private javax.swing.JTextField tenTaiKhoan_TF;
    private javax.swing.JLabel thoiGian_Lbl;
    private javax.swing.JButton thongTinTaiKhoan_Btn;
    private javax.swing.JLabel thongTinTaiKhoan_Lbl;
    private javax.swing.JPanel thongTinTaiKhoan_Pn;
    private javax.swing.JLayeredPane tinhNangCuaTuyChon_LPn;
    private javax.swing.JLayeredPane trangChu_LPn;
    private javax.swing.JPanel trangChu_Pn;
    private javax.swing.JLabel trangThai_Lbl;
    private javax.swing.JTextField trangThai_TF;
    private javax.swing.JButton tuyChon_Btn;
    private javax.swing.JLabel tuyChon_Lbl;
    private javax.swing.JPanel tuyChon_Pn;
    private javax.swing.JButton xacNhan_Btn;
    // End of variables declaration//GEN-END:variables

     
    
    
    public void hienThiThongTinTaiKhoan(String tenDangNhap)
    {
        String query = "select * from NhanVien where tenTK = '" + tenDangNhap + "'";
        try
        {
            Connection connect = Util.getConnection();
            PreparedStatement ps = connect.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            if (rs.next())
            {
                tenTaiKhoan_TF.setText(rs.getString("tenTK"));
                chucVu2_TF.setText(rs.getString("chucVu"));
                CMND_TF.setText(rs.getString("CMND"));
                SDT_TF.setText(rs.getString("SDT"));
                gioiTinh_TF.setText(rs.getString("gioiTinh"));
                tenNhanVien_TF.setText(rs.getString("tenNV"));
                trangThai_TF.setText(rs.getString("trangThai"));
                rs.close();
                ps.close();
                connect.close();
            }
        }catch (SQLException ex)
        {
            System.out.println("Truy van that bai");
        }
    }
    
    public void doiMatKhau(String tenDangNhap, String matKhau)
    {
        String query = "update NhanVien set matKhau = '" + matKhau + "' where tenTK = '" + tenDangNhap + "'";
        try
        {
            Connection connect = Util.getConnection();
            PreparedStatement ps = connect.prepareStatement(query);
            ps.setString(2, matKhau);
            ps.executeUpdate();
            ps.close();
            connect.close();
        }catch (SQLException ex)
        {
            System.out.println("Truy van that bai");
        }
    }
    
}